-- Source Excel file path: ..\datas\GameEvent\Event.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("EventMain", {
	[101001] = {
		EventBgBPPathPC = "/Game/UI/WBP/Activity/Widget/SevenDay/WBP_Activity_SevenDayBG.WBP_Activity_SevenDayBG",
		EventBgSound = "/ui/activity/signin_seven_day_entrance_loop",
		EventDes = "Event_Des_101001",
		EventEndCondition = 6006,
		EventEndTime = 1751446800,
		EventId = 101001,
		EventName = "Event_Title_101001",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/SevenDay/WBP_Activity_SevenDayTitle.WBP_Activity_SevenDayTitle",
		EventStartTime = 1704081600,
		EventTypeId = 101,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/SevenDay/WBP_Activity_SevenDay_M.WBP_Activity_SevenDay_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/SevenDay/WBP_Activity_SevenDay_P.WBP_Activity_SevenDay_P",
		RewardEndTime = 1751446800,
		RewardMailId = 101001,
		ServerEventType = "Login",
		SubExcel = "DailyLogin",
	},
	[103001] = {
		EventBgBPPathPC = "/Game/UI/WBP/RougeLike/Widget/BackGround/WBP_Rouge_Bg01.WBP_Rouge_Bg01",
		EventBgSound = "/ui/activity/common_simple_entrance_loop",
		EventDes = "Event_Des_103001",
		EventId = 103001,
		EventName = "Event_Title_103001",
		EventNameBPPath = "/Game/UI/WBP/RougeLike/Widget/Title/WBP_Rouge_LightLessChasm.WBP_Rouge_LightLessChasm",
		EventSName = "UI_Rou_S1_Title",
		EventTypeId = 103,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/ActivityJump/WBP_Activity_Jump_M.WBP_Activity_Jump_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/ActivityJump/WBP_Activity_Jump_P.WBP_Activity_Jump_P",
	},
	[103002] = {
		EventBgBPPathPC = "/Game/UI/WBP/Abyss/Widget/BackGround/WBP_Abyss_ActivityBG.WBP_Abyss_ActivityBG",
		EventBgSound = "/ui/activity/common_simple_entrance_loop",
		EventDes = "Event_Des_103002",
		EventEndTime = 1751446800,
		EventId = 103002,
		EventName = "Abyss_entry",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/Abyss/WBP_Activity_Abyss_Title.WBP_Activity_Abyss_Title",
		EventRule = "Event_Rule_103002",
		EventSName = "Event_STitle_103002",
		EventStartTime = 1704081600,
		EventTypeId = 103,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/ActivityJump/WBP_Activity_Jump_M.WBP_Activity_Jump_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/ActivityJump/WBP_Activity_Jump_P.WBP_Activity_Jump_P",
		PretextTasks1 = 110109,
		PretextTasks2 = {
			200227,
		},
	},
	[103003] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Gacha/Mobile/PoolWidget/WBP_Gacha_Pool_WidgetAote.WBP_Gacha_Pool_WidgetAote",
		EventBgBPPathPC = "/Game/UI/WBP/Gacha/PC/PoolWidget/WBP_Gacha_Pool_WidgetAote.WBP_Gacha_Pool_WidgetAote",
		EventBgSound = "/ui/activity/common_simple_entrance_loop",
		EventDes = "Event_Des_103003",
		EventEndCondition = 6009,
		EventId = 103003,
		EventName = "Event_Title_103003",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title_AvatarAote.WBP_Activity_TryOut_Title_AvatarAote",
		EventTypeId = 103,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/ActivityJump/WBP_Activity_Jump_M.WBP_Activity_Jump_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/ActivityJump/WBP_Activity_Jump_P.WBP_Activity_Jump_P",
	},
	[103004] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Gacha/Mobile/PoolWidget/WBP_Gacha_Pool_WidgetDafu.WBP_Gacha_Pool_WidgetDafu",
		EventBgBPPathPC = "/Game/UI/WBP/Gacha/PC/PoolWidget/WBP_Gacha_Pool_WidgetDafu.WBP_Gacha_Pool_WidgetDafu",
		EventBgSound = "/ui/activity/common_simple_entrance_loop",
		EventDes = "Event_Des_103004",
		EventEndCondition = 6010,
		EventId = 103004,
		EventName = "Event_Title_103004",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title_AvatarDafu.WBP_Activity_TryOut_Title_AvatarDafu",
		EventTypeId = 103,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/ActivityJump/WBP_Activity_Jump_M.WBP_Activity_Jump_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/ActivityJump/WBP_Activity_Jump_P.WBP_Activity_Jump_P",
	},
	[103005] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Activity/Mobile/ZhiliuEvent/WBP_Activity_ZhiliuEvent_BG.WBP_Activity_ZhiliuEvent_BG",
		EventBgBPPathPC = "/Game/UI/WBP/Activity/PC/ZhiliuEvent/WBP_Activity_ZhiliuEvent_BG.WBP_Activity_ZhiliuEvent_BG",
		EventBgSound = "/ui/activity/zhiliu_entrance_loop",
		EventDes = "Event_Des_103005",
		EventEndTime = 1751446800,
		EventId = 103005,
		EventName = "Event_Title_103005",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/ZhiliuEvent/WBP_Activity_ZhiliuEvent_Title.WBP_Activity_ZhiliuEvent_Title",
		EventStartTime = 1750453200,
		EventTypeId = 103,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/ActivityJump/WBP_Activity_Jump_M.WBP_Activity_Jump_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/ActivityJump/WBP_Activity_Jump_P.WBP_Activity_Jump_P",
		PretextTasks1 = 100307,
		PretextTasks2 = {
			120001,
			120002,
		},
	},
	[105001] = {
		EventBgBPPathPC = "/Game/UI/WBP/Activity/Widget/RechargeRebate/WBP_Activity_RechargeRebate_BG.WBP_Activity_RechargeRebate_BG",
		EventBgSound = "/ui/activity/fanhuan_entrance_loop",
		EventEndTime = 1751446800,
		EventId = 105001,
		EventName = "UI_FeeRefund_Title01",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/RechargeRebate/WBP_Activity_RechargeRebate_Title.WBP_Activity_RechargeRebate_Title",
		EventSName = "UI_FeeRefund_Title02",
		EventStartTime = 1704081600,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/RechargeRebate/WBP_Activity_RechargeRebate_M.WBP_Activity_RechargeRebate_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/RechargeRebate/WBP_Activity_RechargeRebate_P.WBP_Activity_RechargeRebate_P",
	},
	[106001] = {
		EventBgBPPathPC = "/Game/UI/WBP/Activity/Widget/TrainingLevel/WBP_Activity_TrainingLevel_BG.WBP_Activity_TrainingLevel_BG",
		EventBgSound = "/ui/activity/lilian_entrance_loop",
		EventDes = "Event_Des_106001",
		EventEndCondition = 6012,
		EventId = 106001,
		EventName = "Event_Title_106001",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TrainingLevel/WBP_Activity_TrainingLevel_Title.WBP_Activity_TrainingLevel_Title",
		EventTypeId = 106,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/TrainingLevel/WBP_Activity_TrainingLevel_M.WBP_Activity_TrainingLevel_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/TrainingLevel/WBP_Activity_TrainingLevel_P.WBP_Activity_TrainingLevel_P",
	},
	[105101011] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Gacha/Mobile/PoolWidget/WBP_Gacha_Pool_WidgetSaiqi",
		EventBgBPPathPC = "/Game/UI/WBP/Gacha/PC/PoolWidget/WBP_Gacha_Pool_WidgetSaiqi",
		EventBgSound = "/ui/activity/saiqi01_entrance_loop",
		EventDes = "CharTrialEvent_Des_Saiqi",
		EventEndTime = 1751446800,
		EventId = 105101011,
		EventName = "CharTrialEvent_Title_Saiqi",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title.WBP_Activity_TryOut_Title",
		EventStartTime = 1704081600,
		EventTypeId = 105,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_M.WBP_Activity_TryOut_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_P.WBP_Activity_TryOut_P",
	},
	[105102011] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_BG_Saiqi01.WBP_Activity_TryOut_BG_Saiqi01",
		EventBgBPPathPC = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_BG_Saiqi01.WBP_Activity_TryOut_BG_Saiqi01",
		EventBgSound = "/ui/activity/saiqi02_entrance_loop",
		EventDes = "Event_Des_105102011",
		EventEndTime = 1751446800,
		EventId = 105102011,
		EventName = "SkinTrialEvent_Title_Saiqi",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title_SkinSaiqi01.WBP_Activity_TryOut_Title_SkinSaiqi01",
		EventStartTime = 1704081600,
		EventTypeId = 105,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_M.WBP_Activity_TryOut_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_P.WBP_Activity_TryOut_P",
	},
	[105102012] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_BG_Shuimu01",
		EventBgBPPathPC = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_BG_Shuimu01",
		EventBgSound = "/ui/activity/saiqi02_entrance_loop",
		EventDes = "Event_Des_105102012",
		EventEndTime = 1751446800,
		EventId = 105102012,
		EventName = "SkinTrialEvent_Title_Shuimu",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title_SkinSaiqi01.WBP_Activity_TryOut_Title_SkinSaiqi01",
		EventStartTime = 1704081600,
		EventTypeId = 105,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_M.WBP_Activity_TryOut_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_P.WBP_Activity_TryOut_P",
	},
	[105102013] = {
		EventBgBPPathMobile = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_BG_Songlu01",
		EventBgBPPathPC = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_BG_Songlu01",
		EventBgSound = "/ui/activity/saiqi02_entrance_loop",
		EventDes = "Event_Des_105102013",
		EventEndTime = 1751446800,
		EventId = 105102013,
		EventName = "SkinTrialEvent_Title_Songlu",
		EventNameBPPath = "/Game/UI/WBP/Activity/Widget/TryOut/WBP_Activity_TryOut_Title_SkinSaiqi01.WBP_Activity_TryOut_Title_SkinSaiqi01",
		EventStartTime = 1704081600,
		EventTypeId = 105,
		EventUnlockCondition = 4220,
		MobileBluePrint = "/Game/UI/WBP/Activity/Mobile/TryOut/WBP_Activity_TryOut_M.WBP_Activity_TryOut_M",
		PCBluePrint = "/Game/UI/WBP/Activity/PC/TryOut/WBP_Activity_TryOut_P.WBP_Activity_TryOut_P",
	},
})