-- Source Excel file path: ..\datas\Talk\GenderToNpcId.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("GenderToNpcId", {
	[1] = {
		Gender = 1,
		GenderToNpcId = 1,
		GroupId = 1,
		NpcId = 100001,
		SwitchPlayer = "Player",
	},
	[2] = {
		Gender = 0,
		GenderToNpcId = 2,
		GroupId = 1,
		NpcId = 100002,
		SwitchPlayer = "Player",
	},
	[3] = {
		Gender = 0,
		GenderToNpcId = 3,
		GroupId = 2,
		NpcId = 100012,
		SwitchPlayer = "EXPlayer",
	},
	[4] = {
		Gender = 1,
		GenderToNpcId = 4,
		GroupId = 2,
		NpcId = 1000121,
		SwitchPlayer = "EXPlayer",
	},
	[5] = {
		Gender = 0,
		GenderToNpcId = 5,
		GroupId = 3,
		NpcId = 100014,
		SwitchPlayer = "EXPlayer",
	},
	[6] = {
		Gender = 1,
		GenderToNpcId = 6,
		GroupId = 3,
		NpcId = 1000141,
		SwitchPlayer = "EXPlayer",
	},
	[7] = {
		Gender = 0,
		GenderToNpcId = 7,
		GroupId = 4,
		NpcId = 110022,
		SwitchPlayer = "EXPlayer",
	},
	[8] = {
		Gender = 1,
		GenderToNpcId = 8,
		GroupId = 4,
		NpcId = 1100221,
		SwitchPlayer = "EXPlayer",
	},
	[9] = {
		Gender = 0,
		GenderToNpcId = 9,
		GroupId = 5,
		NpcId = 110040,
		SwitchPlayer = "EXPlayer",
	},
	[10] = {
		Gender = 1,
		GenderToNpcId = 10,
		GroupId = 5,
		NpcId = 1100401,
		SwitchPlayer = "EXPlayer",
	},
	[11] = {
		Gender = 0,
		GenderToNpcId = 11,
		GroupId = 6,
		NpcId = 110048,
		SwitchPlayer = "EXPlayer",
	},
	[12] = {
		Gender = 1,
		GenderToNpcId = 12,
		GroupId = 6,
		NpcId = 1100481,
		SwitchPlayer = "EXPlayer",
	},
	[13] = {
		Gender = 1,
		GenderToNpcId = 13,
		GroupId = 7,
		NpcId = 200061,
		SwitchPlayer = "Player",
	},
	[14] = {
		Gender = 0,
		GenderToNpcId = 14,
		GroupId = 7,
		NpcId = 2000611,
		SwitchPlayer = "Player",
	},
	[15] = {
		Gender = 1,
		GenderToNpcId = 15,
		GroupId = 8,
		NpcId = 790008,
		SwitchPlayer = "Player",
	},
	[16] = {
		Gender = 0,
		GenderToNpcId = 16,
		GroupId = 8,
		NpcId = 7900081,
		SwitchPlayer = "Player",
	},
	[17] = {
		Gender = 1,
		GenderToNpcId = 17,
		GroupId = 9,
		NpcId = 700210,
		SwitchPlayer = "Player",
	},
	[18] = {
		Gender = 0,
		GenderToNpcId = 18,
		GroupId = 9,
		NpcId = 7002101,
		SwitchPlayer = "Player",
	},
	[19] = {
		Gender = 1,
		GenderToNpcId = 19,
		GroupId = 10,
		NpcId = 220042,
		SwitchPlayer = "Player",
	},
	[20] = {
		Gender = 0,
		GenderToNpcId = 20,
		GroupId = 10,
		NpcId = 220044,
		SwitchPlayer = "Player",
	},
})