-- Source Excel file path: ..\datas\HardBoss.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("HardBossMain", {
	[1] = {
		AirWallStaticId = 1610010620,
		DifficultyId = {
			1001,
			1002,
			1003,
			1004,
			1005,
			1006,
		},
		DisplayPriority = 1,
		GameModePath = "/Game/AssetDesign/GameMode/HardBoss/BP_EMGameMode_HardBoss00_BossXibi.BP_EMGameMode_HardBoss00_BossXibi",
		HardBossDes = "UI_HardBoss_Des_1",
		HardBossId = 1,
		HardBossName = "UI_HardBoss_Name_1",
		MainIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Xibi.T_Permanent_HardBoss_Xibi",
		MonsterIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Xibi_S.T_Permanent_HardBoss_Xibi_S",
		MonsterId = 8500002,
		MonsterStaticId = 1310010602,
		PosDisplayName = "BP_HardBoss_PlayerStart",
		StorylinePath = "HardBoss/Xibi",
		TeleportId = 9000,
		UnlockCondition = 4120,
	},
	[2] = {
		AirWallStaticId = 1440064,
		DifficultyId = {
			1011,
			1012,
			1013,
			1014,
			1015,
			1016,
		},
		DisplayPriority = 2,
		GameModePath = "/Game/AssetDesign/GameMode/HardBoss/BP_EMGameMode_HardBoss01_BossShijingzhe.BP_EMGameMode_HardBoss01_BossShijingzhe",
		HardBossDes = "UI_HardBoss_Des_2",
		HardBossId = 2,
		HardBossName = "UI_HardBoss_Name_2",
		MainIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_ShiJingZhe.T_Permanent_HardBoss_ShiJingZhe",
		MonsterIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_ShiJingZhe_S.T_Permanent_HardBoss_ShiJingZhe_S",
		MonsterId = 8503002,
		MonsterStaticId = 1440052,
		PosDisplayName = "BP_HardBoss_PlayerStart",
		StorylinePath = "HardBoss/Shijingzhe",
		TeleportId = 9001,
		UnlockCondition = 4120,
	},
	[3] = {
		AirWallStaticId = 1240025,
		DifficultyId = {
			1021,
			1022,
			1023,
			1024,
			1025,
			1026,
		},
		DisplayPriority = 3,
		GameModePath = "/Game/AssetDesign/GameMode/HardBoss/BP_EMGameMode_HardBoss02_BossSaiqi.BP_EMGameMode_HardBoss02_BossSaiqi",
		HardBossDes = "UI_HardBoss_Des_3",
		HardBossId = 3,
		HardBossName = "UI_HardBoss_Name_3",
		MainIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Saiqi.T_Permanent_HardBoss_Saiqi",
		MonsterIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Saiqi_S.T_Permanent_HardBoss_Saiqi_S",
		MonsterId = 8502002,
		MonsterStaticId = 1240027,
		PosDisplayName = "BP_HardBoss_PlayerStart",
		StorylinePath = "HardBoss/Saiqi",
		TeleportId = 9002,
		UnlockCondition = 4120,
	},
	[4] = {
		AirWallStaticId = 1660120,
		DifficultyId = {
			1031,
			1032,
			1033,
			1034,
			1035,
			1036,
		},
		DisplayPriority = 4,
		GameModePath = "/Game/AssetDesign/GameMode/HardBoss/BP_EMGameMode_HardBoss03_BossLianhuo.BP_EMGameMode_HardBoss03_BossLianhuo",
		HardBossDes = "UI_HardBoss_Des_4",
		HardBossId = 4,
		HardBossName = "UI_HardBoss_Name_4",
		MainIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Haier.T_Permanent_HardBoss_Haier",
		MonsterIcon = "/Game/UI/Texture/Dynamic/Image/Permanent/T_Permanent_HardBoss_Haier_S.T_Permanent_HardBoss_Haier_S",
		MonsterId = 8505002,
		MonsterStaticId = 1660121,
		PosDisplayName = "BP_HardBoss_PlayerStart",
		StorylinePath = "HardBoss/Haier",
		TeleportId = 9003,
		UnlockCondition = 2037,
	},
})