-- Source Excel file path: ..\datas\HeadSculpture.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("HeadSculpture", {
	[10001] = {
		Des = "UI_PlayerHead_Des_10001",
		HeadId = 10001,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao.T_Head_Heitao'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao.T_Head_Heitao'",
		Name = "UI_PlayerHead_Name_10001",
	},
	[10002] = {
		Des = "UI_PlayerHead_Des_10002",
		HeadId = 10002,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Baiheng.T_Head_Baiheng'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Baiheng.T_Head_Baiheng'",
		Name = "UI_PlayerHead_Name_10002",
	},
	[10003] = {
		Des = "UI_PlayerHead_Des_10003",
		HeadId = 10003,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Baonu.T_Head_Baonu'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Baonu.T_Head_Baonu'",
		Name = "UI_PlayerHead_Name_10003",
	},
	[10004] = {
		Des = "UI_PlayerHead_Des_10004",
		HeadId = 10004,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Haier.T_Head_Haier'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Haier.T_Head_Haier'",
		Name = "UI_PlayerHead_Name_10004",
	},
	[10006] = {
		Des = "UI_PlayerHead_Des_10006",
		HeadId = 10006,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Landi.T_Head_Landi'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Landi.T_Head_Landi'",
		Name = "UI_PlayerHead_Name_10006",
	},
	[10007] = {
		Des = "UI_PlayerHead_Des_10007",
		HeadId = 10007,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Linen.T_Head_Linen'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Linen.T_Head_Linen'",
		Name = "UI_PlayerHead_Name_10007",
	},
	[10008] = {
		Des = "UI_PlayerHead_Des_10008",
		HeadId = 10008,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Saiqi.T_Head_Saiqi'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Saiqi.T_Head_Saiqi'",
		Name = "UI_PlayerHead_Name_10008",
	},
	[10009] = {
		Des = "UI_PlayerHead_Des_10009",
		HeadId = 10009,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Shuimu.T_Head_Shuimu'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Shuimu.T_Head_Shuimu'",
		Name = "UI_PlayerHead_Name_10009",
	},
	[10010] = {
		Des = "UI_PlayerHead_Des_10010",
		HeadId = 10010,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Songlu.T_Head_Songlu'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Songlu.T_Head_Songlu'",
		Name = "UI_PlayerHead_Name_10010",
	},
	[10011] = {
		Des = "UI_PlayerHead_Des_10011",
		HeadId = 10011,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yuming.T_Head_Yuming'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yuming.T_Head_Yuming'",
		Name = "UI_PlayerHead_Name_10011",
	},
	[10012] = {
		Des = "UI_PlayerHead_Des_10012",
		HeadId = 10012,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Zhangyu.T_Head_Zhangyu'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Zhangyu.T_Head_Zhangyu'",
		Name = "UI_PlayerHead_Name_10012",
	},
	[10013] = {
		Des = "UI_PlayerHead_Des_10013",
		HeadId = 10013,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Dafu.T_Head_Dafu'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Dafu.T_Head_Dafu'",
		Name = "UI_PlayerHead_Name_10013",
	},
	[10014] = {
		Des = "UI_PlayerHead_Des_10014",
		HeadId = 10014,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Feina.T_Head_Feina'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Feina.T_Head_Feina'",
		Name = "UI_PlayerHead_Name_10014",
	},
	[10015] = {
		Des = "UI_PlayerHead_Des_10015",
		HeadId = 10015,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Aote.T_Head_Aote'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Aote.T_Head_Aote'",
		Name = "UI_PlayerHead_Name_10015",
	},
	[10016] = {
		Des = "UI_PlayerHead_Des_10016",
		HeadId = 10016,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Lise.T_Head_Lise'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Lise.T_Head_Lise'",
		Name = "UI_PlayerHead_Name_10016",
	},
	[10017] = {
		Des = "UI_PlayerHead_Des_10017",
		HeadId = 10017,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Maer.T_Head_Maer'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Maer.T_Head_Maer'",
		Name = "UI_PlayerHead_Name_10017",
	},
	[10018] = {
		Des = "UI_PlayerHead_Des_10018",
		HeadId = 10018,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Tuosi.T_Head_Tuosi'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Tuosi.T_Head_Tuosi'",
		Name = "UI_PlayerHead_Name_10018",
	},
	[10019] = {
		Des = "UI_PlayerHead_Des_10019",
		HeadId = 10019,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xibi.T_Head_Xibi'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xibi.T_Head_Xibi'",
		Name = "UI_PlayerHead_Name_10019",
	},
	[10020] = {
		Des = "UI_PlayerHead_Des_10020",
		HeadId = 10020,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xier.T_Head_Xier'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xier.T_Head_Xier'",
		Name = "UI_PlayerHead_Name_10020",
	},
	[10021] = {
		Des = "UI_PlayerHead_Des_10021",
		HeadId = 10021,
		HeadPath = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yeer.T_Head_Yeer'",
		Icon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yeer.T_Head_Yeer'",
		Name = "UI_PlayerHead_Name_10021",
	},
})