-- Source Excel file path: ..\datas\Option.xlsx
local T = {}
T.RT_1 = {
		"UI_OPTION_Swicth_Close",
		"UI_OPTION_Swicth_Open",
	}
T.RT_2 = {
		"UI_EffectQuality_Low",
		"UI_EffectQuality_Middle",
		"UI_EffectQuality_High",
	}
T.RT_3 = {
		1,
		20,
	}
T.RT_4 = {
		"UI_OPTION_Swicth_Close",
		"UI_EffectQuality_Low",
		"UI_EffectQuality_Middle",
		"UI_EffectQuality_High",
	}
T.RT_5 = {
		0,
		10,
	}
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("Option", {
	AimAssist = {
		Cache = "AimAssist",
		CacheText = "UI_OPTION_AimAssist",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "True",
		EMCacheName = "IsOpenHelperAim",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 8,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	AmbientOcclusion = {
		Cache = "AmbientOcclusion",
		CacheText = "UI_OPTION_AmbientOcclusion",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 43,
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	AntiAliasing = {
		Cache = "AntiAliasing",
		CacheText = "UI_OPTION_AntiAliasing",
		ControlType = "UnFold",
		DefaultValue = "2.0",
		DefaultValueM = "2.0",
		EMCacheName = "AntiAliasing",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 35,
		SubOptionDefaultValue = {
			0,
			3,
			3,
		},
		SubOptionName = "UI_OPTION_AntiAliasingQuality",
		SubOptionText = T.RT_2,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_OPTION_Swicth_Close",
			"UI_Option_Dropdown_23",
			"UI_Option_Dropdown_24",
		},
		UnFoldTextM = {
			"UI_OPTION_Swicth_Close",
			"UI_Option_Dropdown_23",
		},
	},
	CameraYawFollow = {
		Cache = "CameraYawFollow",
		CacheText = "UI_OPTION_CameraYawFollow",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "True",
		EMCacheName = "CameraYawFollow",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 6,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	ChildPrivacy = {
		Cache = "ChildPrivacy",
		CacheText = "UI_OPTION_ChildPrivacy",
		CheckText = {
			"49.0",
		},
		ControlType = "Click",
		DefaultValue = "UI_Opition_View",
		DefaultValueM = "UI_Opition_View",
		Region = 1,
		SortId = 65,
		SpecialHide = 1,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	ContentPerformance = {
		Cache = "ContentPerformance",
		CacheText = "UI_OPTION_CrowdDensity",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ContentPerformance",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 33,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_2,
	},
	CustomerService = {
		Cache = "CustomerService",
		CacheText = "UI_OPTION_CustomerService",
		ControlType = "Click",
		DefaultValue = "UI_GameEvent_Goto",
		DefaultValueM = "UI_GameEvent_Goto",
		Region = 1,
		SortId = 61,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	DLSS = {
		Cache = "DLSS",
		CacheText = "UI_OPTION_DLSS",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "False",
		EMCacheName = "DLSS",
		HideOnPhone = true,
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 19,
		SubOptionDefaultValue = {
			1,
		},
		SubOptionName = "UI_OPTION_DLSSQuality",
		SubOptionText = {
			"UI_OPTION_DLSSQuality_1",
			"UI_OPTION_DLSSQuality_2",
			"UI_OPTION_DLSSQuality_3",
			"UI_OPTION_DLSSQuality_4",
			"UI_Option_Dropdown_20",
		},
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	DepthQuality = {
		Cache = "DepthQuality",
		CacheText = "UI_OPTION_DepthQuality",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ConsoleVariable",
		HideOnPhone = true,
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 49,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_2,
	},
	DynamicReflection = {
		Cache = "DynamicReflection",
		CacheText = "UI_OPTION_DynamicReflection",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 38,
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	EffectQuality = {
		Cache = "EffectQuality",
		CacheText = "UI_OPTION_EffectQuality",
		ControlType = "UnFold",
		DefaultValue = "4.0",
		DefaultValueM = "4.0",
		EMCacheName = "GameUserSettings",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 22,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_EffectQuality_ExtremelyLow",
			"UI_EffectQuality_Low",
			"UI_EffectQuality_Middle",
			"UI_EffectQuality_High",
			"UI_EffectQuality_ExtremelyHigh",
		},
		UnFoldTextM = {
			"UI_EffectQuality_ExtremelyLow",
			"UI_EffectQuality_Low",
			"UI_EffectQuality_Middle",
			"UI_EffectQuality_High",
		},
	},
	EnableMobileRotation = {
		Cache = "EnableMobileRotation",
		CacheText = "UI_OPTION_EnableMobileRotation",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "True",
		EMCacheName = "EnableMobileRotation",
		GameHide = 2,
		HideOnPC = true,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 11,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	ExchangeCode = {
		Cache = "ExchangeCode",
		CacheText = "UI_OPTION_ExchangeCode",
		ControlType = "Click",
		DefaultValue = "UI_ActionPoint_Use",
		DefaultValueM = "UI_ActionPoint_Use",
		GameHide = 2,
		Region = 1,
		SortId = 62,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	FallAttackDirection = {
		Cache = "FallAttackDirection",
		CacheText = "UI_OPTION_FallAtkDirection",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "EnableFallAtkDir",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 10,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	ForceFeedback = {
		Cache = "ForceFeedback",
		CacheText = "UI_OPTION_ForceFeedback",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "ForceFeedback",
		GameHide = 2,
		Region = 2,
		RegionName = "UI_OPTION_Gamepad",
		SortId = 15,
		SubOptionDefaultValue = {
			2,
		},
		SubOptionName = "UI_OPTION_ForceFeedbackScale",
		SubOptionText = {
			"UI_OPTION_Strong",
			"UI_OPTION_Medium",
			"UI_OPTION_Weak",
		},
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	Fps = {
		Cache = "Fps",
		CacheText = "UI_OPTION_Fps",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "1.0",
		EMCacheName = "Fps",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 20,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_Option_Dropdown_15",
			"UI_Option_Dropdown_16",
			"UI_Option_Dropdown_17",
			"UI_Option_Dropdown_44",
			"UI_Option_Dropdown_45",
		},
		UnFoldTextM = {
			"UI_Option_Dropdown_15",
			"UI_Option_Dropdown_16",
			"UI_Option_Dropdown_17",
		},
	},
	GamepadPreset = {
		Cache = "GamepadPreset",
		CacheText = "UI_OPTION_GamepadPreset",
		ControlType = "UnFold",
		DefaultValue = "1.0",
		DefaultValueM = "1.0",
		EMCacheName = "GamepadLayout",
		GameHide = 2,
		HideOnPC = true,
		HideOnPhone = true,
		Region = 2,
		RegionName = "UI_OPTION_Gamepad",
		SortId = 14,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
		UnFoldText = {
			"UI_OPTION_Gamepad_Preset1",
			"UI_OPTION_Gamepad_Preset2",
			"UI_OPTION_Gamepad_Preset3",
		},
	},
	HUDSize = {
		Cache = "HUDSize",
		CacheText = "UI_OPTION_HUDSize",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "HUDScale",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 26,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"90%",
			"95%",
			"100%",
			"105%",
			"110%",
		},
		UnFoldTextM = {
			"90%",
			"95%",
			"100%",
		},
	},
	HorizontalSensitivity = {
		Cache = "HorizontalSensitivity",
		CacheText = "UI_OPTION_HorizontalSensitivity",
		ControlType = "Scroll",
		DefaultValue = "10.0",
		DefaultValueM = "10.0",
		EMCacheName = "CameraYaw",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_3,
		SortId = 1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	HorizontalSensitivityOnShooting = {
		Cache = "HorizontalSensitivityOnShooting",
		CacheText = "UI_OPTION_HorizontalSensitivityOnShooting",
		ControlType = "Scroll",
		DefaultValue = "8.0",
		DefaultValueM = "8.0",
		EMCacheName = "CameraYawOnShoot",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_3,
		SortId = 3,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	InterfaceMode = {
		Cache = "InterfaceMode",
		CacheText = "UI_OPTION_InterfaceMode",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		HideOnPhone = true,
		Region = 1,
		RegionName = "UI_Option_Area_12",
		SortId = 18,
		SubOptionDefaultValue = {
			1,
			1,
			2,
			2,
			2,
			2,
		},
		SubOptionName = "UI_OPTION_Resolution",
		SubOptionText = {
			"Dynamic_Resolution",
		},
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_OPTION_InterfaceMode_Full",
			"UI_OPTION_InterfaceMode_NoFrame",
			"UI_OPTION_InterfaceMode_Window4:3",
			"UI_OPTION_InterfaceMode_Window16:9",
			"UI_OPTION_InterfaceMode_Window21:9",
			"UI_OPTION_InterfaceMode_Window23:9",
		},
	},
	LocalWindDetail = {
		Cache = "LocalWindDetail",
		CacheText = "UI_OPTION_LocalWindDetail",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ConsoleVariable",
		HideOnPhone = true,
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 46,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_4,
	},
	LogOffAccount = {
		Cache = "LogOffAccount",
		CacheText = "UI_OPTION_LogOffAccount",
		CheckText = {
			"51.0",
		},
		ControlType = "Click",
		DefaultValue = "UI_OPTION_Logoff",
		DefaultValueM = "UI_OPTION_Logoff",
		Region = 1,
		SortId = 68,
		SpecialHide = 1,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	LongPressLockShooting = {
		Cache = "LongPressLockShooting",
		CacheText = "UI_OPTION_LongPressLockShooting",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "True",
		EMCacheName = "LongPressLockShooting",
		GameHide = 2,
		HideOnPC = true,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 12,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	MaterialFilter = {
		Cache = "MaterialFilter",
		CacheText = "UI_OPTION_MaterialFilter",
		ControlType = "UnFold",
		DefaultValue = "4.0",
		DefaultValueM = "4.0",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 37,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_Option_Dropdown_25",
			"UI_Option_Dropdown_26",
			"UI_Option_Dropdown_27",
			"UI_Option_Dropdown_28",
			"UI_Option_Dropdown_29",
		},
	},
	MaterialQuality = {
		Cache = "MaterialQuality",
		CacheText = "UI_OPTION_MaterialQuality",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "GameUserSettings",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 36,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_2,
	},
	MusicVolume = {
		Cache = "MusicVolume",
		CacheText = "UI_OPTION_MusicVolume",
		ControlType = "Scroll",
		DefaultValue = "10.0",
		DefaultValueM = "10.0",
		EMCacheKey = 2,
		EMCacheName = "FMODVolume",
		Region = 2,
		RegionName = "UI_Option_Area_5",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_5,
		SortId = 54,
		Tag = "Voice",
		TagID = 4,
		TagName = "UI_OPTION_AUDIO",
	},
	MuteBackstage = {
		Cache = "MuteBackstage",
		CacheText = "UI_OPTION_MuteBackstage",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "MuteBackstage",
		HideOnPhone = true,
		Region = 1,
		RegionName = "UI_Option_Area_4",
		SortId = 53,
		SwitchText = T.RT_1,
		Tag = "Voice",
		TagID = 4,
		TagName = "UI_OPTION_AUDIO",
	},
	OverallPreset = {
		Cache = "OverallPreset",
		CacheText = "UI_OPTION_OverallPreset",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "OverallPreset",
		Region = 1,
		RegionName = "UI_Option_Area_12",
		SortId = 16,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_EffectQuality_Low",
			"UI_EffectQuality_Middle",
			"UI_EffectQuality_High",
			"UI_Option_Area_11",
		},
	},
	PostEffect = {
		Cache = "PostEffect",
		CacheText = "UI_OPTION_PostEffect",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 50,
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	PrivacyPolicy = {
		Cache = "PrivacyPolicy",
		CacheText = "UI_OPTION_PrivacyPolicy",
		ControlType = "Click",
		DefaultValue = "UI_Opition_View",
		DefaultValueM = "UI_Opition_View",
		Region = 1,
		SortId = 64,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	ProjectionEdgeStaining = {
		Cache = "ProjectionEdgeStaining",
		CacheText = "UI_OPTION_ProjectionEdgeStaining",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "ConsoleVariable",
		HideOnPC = true,
		HideOnPhone = true,
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 39,
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	RefractiveQuality = {
		Cache = "RefractiveQuality",
		CacheText = "UI_OPTION_RefractiveQuality",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 42,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_4,
	},
	ReleaseStuck = {
		Cache = "ReleaseStuck",
		CacheText = "UI_OPTION_ReleaseStuck",
		ControlType = "Click",
		DefaultValue = "UI_OPTION_ReleaseStuck_Default",
		DefaultValueM = "UI_OPTION_ReleaseStuck_Default",
		GameHide = 2,
		Region = 1,
		SortId = 60,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	ScreenFilter = {
		Cache = "ScreenFilter",
		CacheText = "UI_OPTION_ScreenFilter",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ScreenFilter",
		Region = 1,
		RegionName = "UI_Option_Area_11",
		SortId = 17,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_Option_Dropdown_41",
			"UI_Option_Dropdown_43",
			"UI_Option_Dropdown_42",
		},
	},
	ScreenQuality = {
		Cache = "ScreenQuality",
		CacheText = "UI_OPTION_ScreenQuality",
		ControlType = "UnFold",
		DefaultValue = "1.0",
		DefaultValueM = "1.0",
		EMCacheName = "ScreenQuality",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 51,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_Option_Dropdown_35",
			"UI_Option_Dropdown_36",
			"UI_Option_Dropdown_37",
		},
	},
	ShadowQuality = {
		Cache = "ShadowQuality",
		CacheText = "UI_OPTION_ShadowQuality",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "GameUserSettings",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 21,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_2,
	},
	ShowMonsterName = {
		Cache = "ShowMonsterName",
		CacheText = "UI_OPTION_ShowMonsterName",
		ControlType = "Switch",
		DefaultValue = "False",
		DefaultValueM = "False",
		EMCacheName = "ShowMonsterName",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 13,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	SkillFaceTo = {
		Cache = "SkillFaceTo",
		CacheText = "UI_OPTION_SkillFaceTo",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "False",
		EMCacheName = "SkillFaceTo",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 7,
		SwitchText = {
			"UI_Opition_ToCharacter",
			"UI_Opition_ToCamera",
		},
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	SoundVolume = {
		Cache = "SoundVolume",
		CacheText = "UI_OPTION_SoundVolume",
		ControlType = "Scroll",
		DefaultValue = "10.0",
		DefaultValueM = "10.0",
		EMCacheKey = 1,
		EMCacheName = "FMODVolume",
		Region = 2,
		RegionName = "UI_Option_Area_5",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_5,
		SortId = 56,
		Tag = "Voice",
		TagID = 4,
		TagName = "UI_OPTION_AUDIO",
	},
	SpringArmRate = {
		Cache = "SpringArmRate",
		CacheText = "UI_OPTION_CameraDistance",
		ControlType = "Scroll",
		DefaultValue = "11.0",
		DefaultValueM = "11.0",
		EMCacheName = "SpringArmRate",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		ScrollMappingScale = 10,
		ScrollNum = {
			9,
			13,
		},
		SortId = 5,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	SystemLanguage = {
		Cache = "SystemLanguage",
		CacheText = "UI_OPTION_SystemLanguage",
		ControlType = "UnFold",
		DefaultValue = "1.0",
		DefaultValueM = "1.0",
		EMCacheName = "SystemLanguage",
		Region = 1,
		RegionName = "UI_Option_Area_2",
		SortId = 57,
		Tag = "Language",
		TagID = 5,
		TagName = "UI_OPTION_LANGUAGE",
		UnFoldText = {
			"UI_Language_Text_Chinese",
			"UI_Language_Text_English",
			"UI_Language_Text_Japanese",
			"UI_Language_Text_Korean",
			"UI_Language_Text_TraditionalChinese",
		},
	},
	SystemVoice = {
		Cache = "SystemVoice",
		CacheText = "UI_OPTION_SystemVoice",
		ControlType = "UnFold",
		DefaultValue = "1.0",
		DefaultValueM = "1.0",
		EMCacheName = "SystemVoice",
		Region = 1,
		RegionName = "UI_Option_Area_2",
		SortId = 58,
		Tag = "Language",
		TagID = 5,
		TagName = "UI_OPTION_LANGUAGE",
		UnFoldText = {
			"UI_Language_Voice_Chinese",
			"UI_Language_Voice_English",
			"UI_Language_Voice_Japanese",
			"UI_Language_Voice_Korean",
		},
	},
	TeammateEffects = {
		Cache = "TeammateEffects",
		CacheText = "UI_OPTION_TeammateEffects",
		ControlType = "UnFold",
		DefaultValue = "2.0",
		DefaultValueM = "2.0",
		EMCacheName = "TeammateEffects",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 32,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = {
			"UI_Option_Dropdown_30",
			"UI_Option_Dropdown_31",
			"UI_Option_Dropdown_32",
		},
	},
	TermsOfService = {
		Cache = "TermsOfService",
		CacheText = "UI_OPTION_TermsOfService",
		ControlType = "Click",
		DefaultValue = "UI_Opition_View",
		DefaultValueM = "UI_Opition_View",
		Region = 1,
		SortId = 63,
		SpecialHide = 2,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	ThirdPartySDK = {
		Cache = "ThirdPartySDK",
		CacheText = "UI_OPTION_ThirdPartySDK",
		CheckText = {
			"50.0",
		},
		ControlType = "Click",
		DefaultValue = "UI_Opition_View",
		DefaultValueM = "UI_Opition_View",
		Region = 1,
		SortId = 66,
		SpecialHide = 1,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	TotalVolume = {
		Cache = "TotalVolume",
		CacheText = "UI_OPTION_TotalVolume",
		ControlType = "Scroll",
		DefaultValue = "10.0",
		DefaultValueM = "10.0",
		EMCacheKey = 0,
		EMCacheName = "FMODVolume",
		Region = 1,
		RegionName = "UI_Option_Area_4",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_5,
		SortId = 52,
		Tag = "Voice",
		TagID = 4,
		TagName = "UI_OPTION_AUDIO",
	},
	UpdateOpenLockAim = {
		Cache = "UpdateOpenLockAim",
		CacheText = "UI_OPTION_OpenLockAim",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		EMCacheName = "IsOpenLockAim",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		SortId = 9,
		SwitchText = T.RT_1,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	UserPolicy = {
		Cache = "UserPolicy",
		CacheText = "UI_OPTION_UserPolicy",
		ControlType = "Click",
		DefaultValue = "UI_Opition_View",
		DefaultValueM = "UI_Opition_View",
		Region = 1,
		SortId = 67,
		SpecialHide = 1,
		Tag = "Other",
		TagID = 6,
		TagName = "UI_OPTION_Other",
	},
	VerticalSensitivity = {
		Cache = "VerticalSensitivity",
		CacheText = "UI_OPTION_VerticalSensitivity",
		ControlType = "Scroll",
		DefaultValue = "8.0",
		DefaultValueM = "8.0",
		EMCacheName = "CameraPitch",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_3,
		SortId = 2,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	VerticalSensitivityOnShooting = {
		Cache = "VerticalSensitivityOnShooting",
		CacheText = "UI_OPTION_VerticalSensitivityOnShooting",
		ControlType = "Scroll",
		DefaultValue = "6.0",
		DefaultValueM = "6.0",
		EMCacheName = "CameraPitchOnShoot",
		GameHide = 2,
		Region = 1,
		RegionName = "UI_Option_Area_1",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_3,
		SortId = 4,
		Tag = "Control",
		TagID = 2,
		TagName = "UI_OPTION_CONTROLLER",
	},
	VerticalSync = {
		Cache = "VerticalSync",
		CacheText = "UI_OPTION_VerticalSync",
		ControlType = "Switch",
		DefaultValue = "True",
		DefaultValueM = "True",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 27,
		SwitchText = T.RT_1,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
	},
	VoiceVolume = {
		Cache = "VoiceVolume",
		CacheText = "UI_OPTION_VoiceVolume",
		ControlType = "Scroll",
		DefaultValue = "10.0",
		DefaultValueM = "10.0",
		EMCacheKey = 3,
		EMCacheName = "FMODVolume",
		Region = 2,
		RegionName = "UI_Option_Area_5",
		ScrollMappingScale = 10,
		ScrollNum = T.RT_5,
		SortId = 55,
		Tag = "Voice",
		TagID = 4,
		TagName = "UI_OPTION_AUDIO",
	},
	VolumetricLight = {
		Cache = "VolumetricLight",
		CacheText = "UI_OPTION_VolumetricLight",
		ControlType = "UnFold",
		DefaultValue = "3.0",
		DefaultValueM = "3.0",
		EMCacheName = "ConsoleVariable",
		Region = 2,
		RegionName = "UI_Option_Area_11",
		SortId = 44,
		Tag = "View",
		TagID = 3,
		TagName = "UI_OPTION_DISPLAY",
		UnFoldText = T.RT_4,
	},
})