-- Source Excel file path: ..\datas\RougeLike\RougeLike_Room.xlsx
local T = {}
T.RT_1 = {
		5010,
	}
T.RT_2 = {
		5012,
	}
T.RT_3 = {
		5017,
	}
T.RT_4 = {
		5067,
	}
T.RT_5 = {
		5013,
	}
T.RT_6 = {
		5018,
	}
T.RT_7 = {
		5068,
	}
T.RT_8 = {
		5014,
	}
T.RT_9 = {
		5031,
	}
T.RT_10 = {
		5032,
	}
T.RT_11 = {
		5061,
	}
T.RT_12 = {
		5019,
	}
T.RT_13 = {
		5020,
	}
T.RT_14 = {
		5021,
	}
T.RT_15 = {
		5022,
	}
T.RT_16 = {
		5023,
	}
T.RT_17 = {
		5071,
	}
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("RougeLikeRoom", {
	[101] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat01A.BP_EMGameMode_Prologue_Rou01_Bat01A",
		Name = "RougeLike_RoomName_101",
		RoomId = 101,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[102] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat02A.BP_EMGameMode_Prologue_Rou01_Bat02A",
		Name = "RougeLike_RoomName_101",
		RoomId = 102,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[103] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat03A.BP_EMGameMode_Prologue_Rou01_Bat03A",
		Name = "RougeLike_RoomName_101",
		RoomId = 103,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[104] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat04A.BP_EMGameMode_Prologue_Rou01_Bat04A",
		Name = "RougeLike_RoomName_101",
		RoomId = 104,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[105] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat01A.BP_EMGameMode_Prologue_Rou01_Bat01A",
		Name = "RougeLike_RoomName_101",
		RoomId = 105,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[106] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat02A.BP_EMGameMode_Prologue_Rou01_Bat02A",
		Name = "RougeLike_RoomName_101",
		RoomId = 106,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[107] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat03A.BP_EMGameMode_Prologue_Rou01_Bat03A",
		Name = "RougeLike_RoomName_101",
		RoomId = 107,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[108] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat04A.BP_EMGameMode_Prologue_Rou01_Bat04A",
		Name = "RougeLike_RoomName_101",
		RoomId = 108,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[109] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat01A.BP_EMGameMode_Prologue_Rou01_Bat01A",
		Name = "RougeLike_RoomName_101",
		RoomId = 109,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[110] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat02A.BP_EMGameMode_Prologue_Rou01_Bat02A",
		Name = "RougeLike_RoomName_101",
		RoomId = 110,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[111] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat03A.BP_EMGameMode_Prologue_Rou01_Bat03A",
		Name = "RougeLike_RoomName_101",
		RoomId = 111,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[112] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat04A.BP_EMGameMode_Prologue_Rou01_Bat04A",
		Name = "RougeLike_RoomName_101",
		RoomId = 112,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[113] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat01A.BP_EMGameMode_Prologue_Rou01_Bat01A",
		Name = "RougeLike_RoomName_101",
		RoomId = 113,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[114] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat02A.BP_EMGameMode_Prologue_Rou01_Bat02A",
		Name = "RougeLike_RoomName_101",
		RoomId = 114,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[115] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat03A.BP_EMGameMode_Prologue_Rou01_Bat03A",
		Name = "RougeLike_RoomName_101",
		RoomId = 115,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[116] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 13,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 90,
		EndPointsExtras = 150,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat04A.BP_EMGameMode_Prologue_Rou01_Bat04A",
		Name = "RougeLike_RoomName_101",
		RoomId = 116,
		RoomSubType = 1,
		RoomType = 1,
		RoomWeight = 100,
		TokenAward = 160,
	},
	[151] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat101B.BP_EMGameMode_Prologue_Rou01_Bat101B",
		Name = "RougeLike_RoomName_102",
		RoomId = 151,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[152] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat102B.BP_EMGameMode_Prologue_Rou01_Bat102B",
		Name = "RougeLike_RoomName_102",
		RoomId = 152,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[154] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat104B.BP_EMGameMode_Prologue_Rou01_Bat104B",
		Name = "RougeLike_RoomName_102",
		RoomId = 154,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[155] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat105B.BP_EMGameMode_Prologue_Rou01_Bat105B",
		Name = "RougeLike_RoomName_102",
		RoomId = 155,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[156] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat106B.BP_EMGameMode_Prologue_Rou01_Bat106B",
		Name = "RougeLike_RoomName_102",
		RoomId = 156,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[157] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat107B.BP_EMGameMode_Prologue_Rou01_Bat107B",
		Name = "RougeLike_RoomName_102",
		RoomId = 157,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[158] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat108B.BP_EMGameMode_Prologue_Rou01_Bat108B",
		Name = "RougeLike_RoomName_102",
		RoomId = 158,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[159] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat109B.BP_EMGameMode_Prologue_Rou01_Bat109B",
		Name = "RougeLike_RoomName_102",
		RoomId = 159,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[160] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat110B.BP_EMGameMode_Prologue_Rou01_Bat110B",
		Name = "RougeLike_RoomName_102",
		RoomId = 160,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[161] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat111B.BP_EMGameMode_Prologue_Rou01_Bat111B",
		Name = "RougeLike_RoomName_102",
		RoomId = 161,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[162] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat112B.BP_EMGameMode_Prologue_Rou01_Bat112B",
		Name = "RougeLike_RoomName_102",
		RoomId = 162,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[163] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat113B.BP_EMGameMode_Prologue_Rou01_Bat113B",
		Name = "RougeLike_RoomName_102",
		RoomId = 163,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[164] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat114B.BP_EMGameMode_Prologue_Rou01_Bat114B",
		Name = "RougeLike_RoomName_102",
		RoomId = 164,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[165] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat201B.BP_EMGameMode_Prologue_Rou01_Bat201B",
		Name = "RougeLike_RoomName_102",
		RoomId = 165,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[166] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat202B.BP_EMGameMode_Prologue_Rou01_Bat202B",
		Name = "RougeLike_RoomName_102",
		RoomId = 166,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[168] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat204B.BP_EMGameMode_Prologue_Rou01_Bat204B",
		Name = "RougeLike_RoomName_102",
		RoomId = 168,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[169] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat205B.BP_EMGameMode_Prologue_Rou01_Bat205B",
		Name = "RougeLike_RoomName_102",
		RoomId = 169,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[170] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat206B.BP_EMGameMode_Prologue_Rou01_Bat206B",
		Name = "RougeLike_RoomName_102",
		RoomId = 170,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[171] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat207B.BP_EMGameMode_Prologue_Rou01_Bat207B",
		Name = "RougeLike_RoomName_102",
		RoomId = 171,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[172] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat208B.BP_EMGameMode_Prologue_Rou01_Bat208B",
		Name = "RougeLike_RoomName_102",
		RoomId = 172,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[173] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat209B.BP_EMGameMode_Prologue_Rou01_Bat209B",
		Name = "RougeLike_RoomName_102",
		RoomId = 173,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[174] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat210B.BP_EMGameMode_Prologue_Rou01_Bat210B",
		Name = "RougeLike_RoomName_102",
		RoomId = 174,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[175] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat211B.BP_EMGameMode_Prologue_Rou01_Bat211B",
		Name = "RougeLike_RoomName_102",
		RoomId = 175,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[176] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat212B.BP_EMGameMode_Prologue_Rou01_Bat212B",
		Name = "RougeLike_RoomName_102",
		RoomId = 176,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[177] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat213B.BP_EMGameMode_Prologue_Rou01_Bat213B",
		Name = "RougeLike_RoomName_102",
		RoomId = 177,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[178] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat214B.BP_EMGameMode_Prologue_Rou01_Bat214B",
		Name = "RougeLike_RoomName_102",
		RoomId = 178,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[179] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat301B.BP_EMGameMode_Prologue_Rou01_Bat301B",
		Name = "RougeLike_RoomName_102",
		RoomId = 179,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[180] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat302B.BP_EMGameMode_Prologue_Rou01_Bat302B",
		Name = "RougeLike_RoomName_102",
		RoomId = 180,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[182] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat304B.BP_EMGameMode_Prologue_Rou01_Bat304B",
		Name = "RougeLike_RoomName_102",
		RoomId = 182,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[183] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat305B.BP_EMGameMode_Prologue_Rou01_Bat305B",
		Name = "RougeLike_RoomName_102",
		RoomId = 183,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[184] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat306B.BP_EMGameMode_Prologue_Rou01_Bat306B",
		Name = "RougeLike_RoomName_102",
		RoomId = 184,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[185] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat307B.BP_EMGameMode_Prologue_Rou01_Bat307B",
		Name = "RougeLike_RoomName_102",
		RoomId = 185,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[186] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat01_Art.Prologue_Rou01_Bat01_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat01A_Design.Prologue_Rou01_Bat01A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat308B.BP_EMGameMode_Prologue_Rou01_Bat308B",
		Name = "RougeLike_RoomName_102",
		RoomId = 186,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[187] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat309B.BP_EMGameMode_Prologue_Rou01_Bat309B",
		Name = "RougeLike_RoomName_102",
		RoomId = 187,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[188] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat02_Art.Prologue_Rou01_Bat02_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat02A_Design.Prologue_Rou01_Bat02A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat310B.BP_EMGameMode_Prologue_Rou01_Bat310B",
		Name = "RougeLike_RoomName_102",
		RoomId = 188,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[189] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat311B.BP_EMGameMode_Prologue_Rou01_Bat311B",
		Name = "RougeLike_RoomName_102",
		RoomId = 189,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[190] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat03_Art.Prologue_Rou01_Bat03_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat03A_Design.Prologue_Rou01_Bat03A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat312B.BP_EMGameMode_Prologue_Rou01_Bat312B",
		Name = "RougeLike_RoomName_102",
		RoomId = 190,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[191] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat313B.BP_EMGameMode_Prologue_Rou01_Bat313B",
		Name = "RougeLike_RoomName_102",
		RoomId = 191,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[192] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		BlessingAward = 15,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Bat04A_Design.Prologue_Rou01_Bat04A_Design",
		EndPointsBase = 120,
		EndPointsExtras = 200,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Bat314B.BP_EMGameMode_Prologue_Rou01_Bat314B",
		Name = "RougeLike_RoomName_102",
		RoomId = 192,
		RoomSubType = 1,
		RoomType = 6,
		RoomWeight = 100,
		TokenAward = 200,
	},
	[201] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite01A_Design.Prologue_Rou01_Elite01A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite01A.BP_EMGameMode_Prologue_Rou01_Elite01A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_1,
		RoomId = 201,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[202] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite01A_Design.Prologue_Rou01_Elite01A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite01A.BP_EMGameMode_Prologue_Rou01_Elite01A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_2,
		RoomId = 202,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[203] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite01A_Design.Prologue_Rou01_Elite01A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite01A.BP_EMGameMode_Prologue_Rou01_Elite01A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_3,
		RoomId = 203,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[204] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite01A_Design.Prologue_Rou01_Elite01A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite01A.BP_EMGameMode_Prologue_Rou01_Elite01A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_4,
		RoomId = 204,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[205] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite02A_Design.Prologue_Rou01_Elite02A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite02A.BP_EMGameMode_Prologue_Rou01_Elite02A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_1,
		RoomId = 205,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[206] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite02A_Design.Prologue_Rou01_Elite02A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite02A.BP_EMGameMode_Prologue_Rou01_Elite02A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_2,
		RoomId = 206,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[207] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite02A_Design.Prologue_Rou01_Elite02A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite02A.BP_EMGameMode_Prologue_Rou01_Elite02A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_3,
		RoomId = 207,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[208] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite02A_Design.Prologue_Rou01_Elite02A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite02A.BP_EMGameMode_Prologue_Rou01_Elite02A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_4,
		RoomId = 208,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100,
		TokenAward = 360,
	},
	[209] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite03A_Design.Prologue_Rou01_Elite03A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite03A.BP_EMGameMode_Prologue_Rou01_Elite03A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_5,
		RoomId = 209,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[210] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite03A_Design.Prologue_Rou01_Elite03A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite03A.BP_EMGameMode_Prologue_Rou01_Elite03A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_6,
		RoomId = 210,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[211] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite03A_Design.Prologue_Rou01_Elite03A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite03A.BP_EMGameMode_Prologue_Rou01_Elite03A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_7,
		RoomId = 211,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[212] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite04A_Design.Prologue_Rou01_Elite04A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite04A.BP_EMGameMode_Prologue_Rou01_Elite04A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_5,
		RoomId = 212,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[213] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite04A_Design.Prologue_Rou01_Elite04A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite04A.BP_EMGameMode_Prologue_Rou01_Elite04A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_6,
		RoomId = 213,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[214] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		BlessingAward = 12,
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Elite04A_Design.Prologue_Rou01_Elite04A_Design",
		EndPointsBase = 210,
		EndPointsExtras = 300,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Elite04A.BP_EMGameMode_Prologue_Rou01_Elite04A",
		Name = "RougeLike_RoomName_201",
		RoomCondition = T.RT_7,
		RoomId = 214,
		RoomSubType = 1,
		RoomType = 2,
		RoomWeight = 100000,
		TokenAward = 360,
	},
	[301] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event19.T_Rouge_Event19'",
		EventSelect = {
			[1] = 1011,
			[2] = 1012,
		},
		EventStoryline = "Rogue/RouEvent_301",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_301",
		RLArchiveId = 1,
		RoomId = 301,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 300,
	},
	[302] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event01.T_Rouge_Event01'",
		EventSelect = {
			[1] = 1016,
			[2] = 1017,
		},
		EventStoryline = "Rogue/RouEvent_302",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_302",
		RLArchiveId = 2,
		RoomCondition = {
			5015,
			5016,
		},
		RoomId = 302,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[303] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event02.T_Rouge_Event02'",
		EventSelect = {
			[1] = 1021,
			[2] = 1022,
		},
		EventStoryline = "Rogue/RouEvent_303",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_303",
		RLArchiveId = 3,
		RoomId = 303,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[304] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event18.T_Rouge_Event18'",
		EventSelect = {
			[1] = 1026,
			[2] = 1027,
			[3] = 1028,
		},
		EventStoryline = "Rogue/RouEvent_304",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_304",
		RLArchiveId = 4,
		RoomId = 304,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[305] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event03.T_Rouge_Event03'",
		EventSelect = {
			[1] = 1031,
			[2] = 1032,
			[3] = 1033,
		},
		EventStoryline = "Rogue/RouEvent_305",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_305",
		RLArchiveId = 5,
		RoomCondition = T.RT_8,
		RoomId = 305,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[306] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event04.T_Rouge_Event04'",
		EventSelect = {
			[1] = 1036,
			[2] = 1037,
		},
		EventStoryline = "Rogue/RouEvent_306",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_306",
		RLArchiveId = 6,
		RoomId = 306,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 500,
	},
	[307] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event05.T_Rouge_Event05'",
		EventSelect = {
			[1] = 1041,
			[2] = 1042,
		},
		EventStoryline = "Rogue/RouEvent_307",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_307",
		RLArchiveId = 7,
		RoomId = 307,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[308] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Prologue_Rou01_Evebat01_Design.Prologue_Rou01_Evebat01_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event06.T_Rouge_Event06'",
		EventSelect = {
			[1] = 1046,
			[2] = 1047,
		},
		EventStoryline = "Rogue/RouEvent_308",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve308A.BP_EMGameMode_Prologue_Rou01_Eve308A",
		Name = "RougeLike_RoomName_308",
		RLArchiveId = 8,
		RoomId = 308,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[309] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event07.T_Rouge_Event07'",
		EventSelect = {
			[1] = 1051,
			[2] = 1052,
		},
		EventStoryline = "Rogue/RouEvent_309",
		FrontRoom = {
			308,
		},
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_309",
		RLArchiveId = 9,
		RoomId = 309,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 500,
	},
	[310] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event08.T_Rouge_Event08'",
		EventSelect = {
			[1] = 1056,
			[2] = 1057,
		},
		EventStoryline = "Rogue/RouEvent_310",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_310",
		RLArchiveId = 10,
		RoomId = 310,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[311] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event09.T_Rouge_Event09'",
		EventSelect = {
			[1] = 1061,
			[2] = 1062,
		},
		EventStoryline = "Rogue/RouEvent_311",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_311",
		RLArchiveId = 11,
		RoomCondition = {
			5160,
		},
		RoomId = 311,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[312] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event10.T_Rouge_Event10'",
		EventSelect = {
			[1] = 1066,
			[2] = 1067,
		},
		EventStoryline = "Rogue/RouEvent_312",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_312",
		RLArchiveId = 12,
		RoomId = 312,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 200,
	},
	[313] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event11.T_Rouge_Event11'",
		EventSelect = {
			[1] = 1071,
			[2] = 1072,
		},
		EventStoryline = "Rogue/RouEvent_313",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_313",
		RLArchiveId = 13,
		RoomCondition = {
			5159,
		},
		RoomId = 313,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 300,
	},
	[314] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event12.T_Rouge_Event12'",
		EventSelect = {
			[1] = 1076,
			[2] = 1077,
		},
		EventStoryline = "Rogue/RouEvent_314",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_314",
		RLArchiveId = 14,
		RoomCondition = T.RT_8,
		RoomId = 314,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 300,
	},
	[315] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event13.T_Rouge_Event13'",
		EventSelect = {
			[1] = 1081,
			[2] = 1082,
			[3] = 1083,
		},
		EventStoryline = "Rogue/RouEvent_315",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_315",
		RLArchiveId = 15,
		RoomId = 315,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 500,
	},
	[316] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event14_2.T_Rouge_Event14_2'",
		EventSelect = {
			[1] = 1086,
			[2] = 1087,
			[3] = 1088,
		},
		EventStoryline = "Rogue/RouEvent_316",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_316",
		RLArchiveId = 16,
		RoomId = 316,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 500,
	},
	[317] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event15.T_Rouge_Event15'",
		EventSelect = {
			[1] = 1091,
			[2] = 1092,
			[3] = 1093,
		},
		EventStoryline = "Rogue/RouEvent_317",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_317",
		RLArchiveId = 17,
		RoomId = 317,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 200,
	},
	[318] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event01.T_Rouge_Event01'",
		EventSelect = {
			[1] = 1096,
			[2] = 1097,
		},
		EventStoryline = "Rogue/RouEvent_302",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_318",
		RLArchiveId = 18,
		RoomCondition = {
			5008,
			5009,
		},
		RoomId = 318,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[319] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event02.T_Rouge_Event02'",
		EventSelect = {
			[1] = 1101,
			[2] = 1102,
		},
		EventStoryline = "Rogue/RouEvent_303",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01A.BP_EMGameMode_Prologue_Rou01_Eve01A",
		Name = "RougeLike_RoomName_319",
		RLArchiveId = 19,
		RoomId = 319,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[320] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02A_Design.Prologue_Rou01_Eve02A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event13.T_Rouge_Event13'",
		EventSelect = {
			[1] = 1106,
			[2] = 1107,
			[3] = 1108,
		},
		EventStoryline = "Rogue/RouEvent_315",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02A.BP_EMGameMode_Prologue_Rou01_Eve02A",
		Name = "RougeLike_RoomName_320",
		RLArchiveId = 20,
		RoomId = 320,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 500,
	},
	[381] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Bat04_Art.Prologue_Rou01_Bat04_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Game01_Design.Prologue_Rou01_Game01_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event15.T_Rouge_Event15'",
		EventSelect = {
			[1] = 2001,
		},
		EventStoryline = "Rogue/RouEvent_381",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Game01A.BP_EMGameMode_Prologue_Rou01_Game01A",
		Name = "RougeLike_RoomName_381",
		RLArchiveId = 21,
		RoomCondition = {
			5065,
		},
		RoomId = 381,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 1000,
	},
	[382] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01A_Design.Prologue_Rou01_Eve01A_Design",
		EndPointsBase = 90,
		EventMainIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/RougeLike/T_Rouge_Event15.T_Rouge_Event15'",
		EventSelect = {
			[1] = 2003,
			[2] = 2004,
		},
		EventStoryline = "Rogue/RouEvent_382",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Game02A.BP_EMGameMode_Prologue_Rou01_Game02A",
		Name = "RougeLike_RoomName_382",
		RLArchiveId = 22,
		RoomCondition = {
			5064,
		},
		RoomId = 382,
		RoomSubType = 1,
		RoomType = 3,
		RoomWeight = 100,
	},
	[401] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01B_Design.Prologue_Rou01_Eve01B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01B.BP_EMGameMode_Prologue_Rou01_Eve01B",
		Name = "RougeLike_RoomName_401",
		RoomId = 401,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 100,
		ShopRandom = {
			1,
		},
	},
	[402] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02B_Design.Prologue_Rou01_Eve02B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02B.BP_EMGameMode_Prologue_Rou01_Eve02B",
		Name = "RougeLike_RoomName_401",
		RoomId = 402,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 100,
		ShopRandom = {
			2,
		},
	},
	[403] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01B_Design.Prologue_Rou01_Eve01B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01B.BP_EMGameMode_Prologue_Rou01_Eve01B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = {
			5029,
		},
		RoomId = 403,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 300,
		ShopRandom = {
			3,
		},
	},
	[404] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02B_Design.Prologue_Rou01_Eve02B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02B.BP_EMGameMode_Prologue_Rou01_Eve02B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = {
			5030,
		},
		RoomId = 404,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 600,
		ShopRandom = {
			4,
		},
	},
	[405] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01B_Design.Prologue_Rou01_Eve01B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01B.BP_EMGameMode_Prologue_Rou01_Eve01B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_9,
		RoomId = 405,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 1000,
		ShopRandom = {
			5,
		},
	},
	[406] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02B_Design.Prologue_Rou01_Eve02B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02B.BP_EMGameMode_Prologue_Rou01_Eve02B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_9,
		RoomId = 406,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 1000,
		ShopRandom = {
			6,
		},
	},
	[407] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01B_Design.Prologue_Rou01_Eve01B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01B.BP_EMGameMode_Prologue_Rou01_Eve01B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_10,
		RoomId = 407,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 2000,
		ShopRandom = {
			7,
		},
	},
	[408] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02B_Design.Prologue_Rou01_Eve02B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02B.BP_EMGameMode_Prologue_Rou01_Eve02B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_10,
		RoomId = 408,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 2000,
		ShopRandom = {
			8,
		},
	},
	[409] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve01_Art.Prologue_Rou01_Eve01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve01B_Design.Prologue_Rou01_Eve01B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve01B.BP_EMGameMode_Prologue_Rou01_Eve01B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_11,
		RoomId = 409,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 600,
		ShopRandom = {
			101,
		},
	},
	[410] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Eve02_Art.Prologue_Rou01_Eve02_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Eve02B_Design.Prologue_Rou01_Eve02B_Design",
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Eve02B.BP_EMGameMode_Prologue_Rou01_Eve02B",
		Name = "RougeLike_RoomName_401",
		RoomCondition = T.RT_11,
		RoomId = 410,
		RoomSubType = 1,
		RoomType = 4,
		RoomWeight = 300,
		ShopRandom = {
			102,
		},
	},
	[501] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 2500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A.BP_EMGameMode_Prologue_Rou01_Boss01A",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_12,
		RoomId = 501,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[502] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 3700,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A_2.BP_EMGameMode_Prologue_Rou01_Boss01A_2",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_13,
		RoomId = 502,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[503] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 5500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A_3.BP_EMGameMode_Prologue_Rou01_Boss01A_3",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_14,
		RoomId = 503,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[504] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 8000,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A_4.BP_EMGameMode_Prologue_Rou01_Boss01A_4",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_15,
		RoomId = 504,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[505] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 12500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A_5.BP_EMGameMode_Prologue_Rou01_Boss01A_5",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_16,
		RoomId = 505,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[506] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss01A_Design.Prologue_Rou01_Boss01A_Design",
		EndPointsBase = 20500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss01A_6.BP_EMGameMode_Prologue_Rou01_Boss01A_6",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_17,
		RoomId = 506,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[507] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 2500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A.BP_EMGameMode_Prologue_Rou01_Boss02A",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_12,
		RoomId = 507,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[508] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 3700,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A_2.BP_EMGameMode_Prologue_Rou01_Boss02A_2",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_13,
		RoomId = 508,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[509] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 5500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A_3.BP_EMGameMode_Prologue_Rou01_Boss02A_3",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_14,
		RoomId = 509,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[510] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 8000,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A_4.BP_EMGameMode_Prologue_Rou01_Boss02A_4",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_15,
		RoomId = 510,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[511] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 12500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A_5.BP_EMGameMode_Prologue_Rou01_Boss02A_5",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_16,
		RoomId = 511,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[512] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss02A_Design.Prologue_Rou01_Boss02A_Design",
		EndPointsBase = 20500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss02A_6.BP_EMGameMode_Prologue_Rou01_Boss02A_6",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_17,
		RoomId = 512,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[513] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 2500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A.BP_EMGameMode_Prologue_Rou01_Boss03A",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_12,
		RoomId = 513,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[514] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 3700,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A_2.BP_EMGameMode_Prologue_Rou01_Boss03A_2",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_13,
		RoomId = 514,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[515] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 5500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A_3.BP_EMGameMode_Prologue_Rou01_Boss03A_3",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_14,
		RoomId = 515,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[516] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 8000,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A_4.BP_EMGameMode_Prologue_Rou01_Boss03A_4",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_15,
		RoomId = 516,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[517] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 12500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A_5.BP_EMGameMode_Prologue_Rou01_Boss03A_5",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_16,
		RoomId = 517,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
	[518] = {
		ArtDataPath = "/Game/Maps/Datas/Data_Art/Prologue/Prologue_Rou01_Boss01_Art.Prologue_Rou01_Boss01_Art",
		DesignDataPath = "/Game/Maps/Datas/Data_Design/Prologue/Roug01_Design/Prologue_Rou01_Boss03A_Design.Prologue_Rou01_Boss03A_Design",
		EndPointsBase = 20500,
		GameModePath = "/Game/AssetDesign/GameMode/Prologue/Roug01/BP_EMGameMode_Prologue_Rou01_Boss03A_6.BP_EMGameMode_Prologue_Rou01_Boss03A_6",
		Name = "RougeLike_RoomName_501",
		RoomCondition = T.RT_17,
		RoomId = 518,
		RoomSubType = 1,
		RoomType = 5,
		RoomWeight = 100,
	},
})