-- Source Excel file path: ..\datas\Skin.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("Skin", {
	[1101] = {
		CharId = 1101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarHeitao",
		NpcSkinModelId = 81101,
		SkinDescribe = "UI_CHAR_NAME_1101",
		SkinId = 1101,
		SkinModelId = 1101,
		SkinName = "UI_CHAR_NAME_1101",
	},
	[1103] = {
		CharId = 1103,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Tuosi",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarTuosi",
		NpcSkinModelId = 81103,
		SkinDescribe = "UI_CHAR_NAME_1103",
		SkinId = 1103,
		SkinModelId = 1103,
		SkinName = "UI_CHAR_NAME_1103",
	},
	[1104] = {
		CharId = 1104,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarHeitao",
		NpcSkinModelId = 81104,
		SkinDescribe = "UI_CHAR_NAME_1104",
		SkinId = 1104,
		SkinModelId = 1104,
		SkinName = "UI_CHAR_NAME_1104",
	},
	[1501] = {
		CharId = 1501,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarHeitao",
		NpcSkinModelId = 81501,
		SkinDescribe = "UI_CHAR_NAME_1501",
		SkinId = 1501,
		SkinModelId = 1501,
		SkinName = "UI_CHAR_NAME_1501",
	},
	[1502] = {
		CharId = 1502,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarNifu",
		NpcSkinModelId = 81502,
		SkinDescribe = "UI_CHAR_NAME_1502",
		SkinId = 1502,
		SkinModelId = 1502,
		SkinName = "UI_CHAR_NAME_1502",
	},
	[1503] = {
		CharId = 1503,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarKezhou",
		NpcSkinModelId = 81503,
		SkinDescribe = "UI_CHAR_NAME_1503",
		SkinId = 1503,
		SkinModelId = 1503,
		SkinName = "UI_CHAR_NAME_1503",
	},
	[1801] = {
		CharId = 1801,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Feina",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarFeina",
		NpcSkinModelId = 81801,
		SkinDescribe = "UI_CHAR_NAME_1801",
		SkinId = 1801,
		SkinModelId = 1801,
		SkinName = "UI_CHAR_NAME_1801",
	},
	[2101] = {
		CharId = 2101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Shuimu",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarShuimu",
		NpcSkinModelId = 82101,
		SkinDescribe = "UI_CHAR_NAME_2101",
		SkinId = 2101,
		SkinModelId = 2101,
		SkinName = "UI_CHAR_NAME_2101",
	},
	[2301] = {
		CharId = 2301,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Zhangyu",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarZhangyu",
		NpcSkinModelId = 82301,
		SkinDescribe = "UI_CHAR_NAME_2301",
		SkinId = 2301,
		SkinModelId = 2301,
		SkinName = "UI_CHAR_NAME_2301",
	},
	[2401] = {
		CharId = 2401,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Baiheng",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarBaiheng",
		NpcSkinModelId = 82401,
		SkinDescribe = "UI_CHAR_NAME_2401",
		SkinId = 2401,
		SkinModelId = 2401,
		SkinName = "UI_CHAR_NAME_2401",
	},
	[3101] = {
		CharId = 3101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Linen",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarLinen",
		NpcSkinModelId = 83101,
		SkinDescribe = "UI_CHAR_NAME_3101",
		SkinId = 3101,
		SkinModelId = 3101,
		SkinName = "UI_CHAR_NAME_3101",
	},
	[3102] = {
		CharId = 3102,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xier",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarXier",
		NpcSkinModelId = 83102,
		SkinDescribe = "UI_CHAR_NAME_3102",
		SkinId = 3102,
		SkinModelId = 3102,
		SkinName = "UI_CHAR_NAME_3102",
	},
	[3103] = {
		CharId = 3103,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yeer",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarYeer",
		NpcSkinModelId = 83103,
		SkinDescribe = "UI_CHAR_NAME_3103",
		SkinId = 3103,
		SkinModelId = 3103,
		SkinName = "UI_CHAR_NAME_3103",
	},
	[3201] = {
		CharId = 3201,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Haier",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarHaier",
		NpcSkinModelId = 83201,
		SkinDescribe = "UI_CHAR_NAME_3201",
		SkinId = 3201,
		SkinModelId = 3201,
		SkinName = "UI_CHAR_NAME_3201",
	},
	[3301] = {
		CharId = 3301,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Maer",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarMaer",
		NpcSkinModelId = 83301,
		SkinDescribe = "UI_CHAR_NAME_3301",
		SkinId = 3301,
		SkinModelId = 3301,
		SkinName = "UI_CHAR_NAME_3301",
	},
	[4101] = {
		CharId = 4101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Heitao",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarLise",
		NpcSkinModelId = 84101,
		SkinDescribe = "UI_CHAR_NAME_4101",
		SkinId = 4101,
		SkinModelId = 4101,
		SkinName = "UI_CHAR_NAME_4101",
	},
	[4102] = {
		CharId = 4102,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xibi",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarZhiliu",
		NpcSkinModelId = 84102,
		SkinDescribe = "UI_CHAR_NAME_4102",
		SkinId = 4102,
		SkinModelId = 4102,
		SkinName = "UI_CHAR_NAME_4102",
	},
	[4201] = {
		CharId = 4201,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Yuming",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarYuming",
		NpcSkinModelId = 84201,
		SkinDescribe = "UI_CHAR_NAME_4201",
		SkinId = 4201,
		SkinModelId = 4201,
		SkinName = "UI_CHAR_NAME_4201",
	},
	[4202] = {
		CharId = 4202,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Landi",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarLandi",
		NpcSkinModelId = 84202,
		SkinDescribe = "UI_CHAR_NAME_4202",
		SkinId = 4202,
		SkinModelId = 4202,
		SkinName = "UI_CHAR_NAME_4202",
	},
	[4301] = {
		CharId = 4301,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Xibi",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarXibi",
		NpcSkinModelId = 84301,
		SkinDescribe = "UI_CHAR_NAME_4301",
		SkinId = 4301,
		SkinModelId = 4301,
		SkinName = "UI_CHAR_NAME_4301",
	},
	[5101] = {
		CharId = 5101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Songlu",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarSonglu",
		NpcSkinModelId = 85101,
		SkinDescribe = "UI_CHAR_NAME_5101",
		SkinId = 5101,
		SkinModelId = 5101,
		SkinName = "UI_CHAR_NAME_5101",
	},
	[5102] = {
		CharId = 5102,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Aote",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarAote",
		NpcSkinModelId = 85102,
		SkinDescribe = "UI_CHAR_NAME_5102",
		SkinId = 5102,
		SkinModelId = 5102,
		SkinName = "UI_CHAR_NAME_5102",
	},
	[5301] = {
		CharId = 5301,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Saiqi",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarSaiqi",
		NpcSkinModelId = 85301,
		SkinDescribe = "UI_CHAR_NAME_5301",
		SkinId = 5301,
		SkinModelId = 5301,
		SkinName = "UI_CHAR_NAME_5301",
	},
	[5401] = {
		CharId = 5401,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Dafu",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarDafu",
		NpcSkinModelId = 85401,
		SkinDescribe = "UI_CHAR_NAME_1101",
		SkinId = 5401,
		SkinModelId = 5401,
		SkinName = "UI_CHAR_NAME_1101",
	},
	[210102] = {
		BigIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Bust/Avatar/T_Bust_Shuimu01.T_Bust_Shuimu01'",
		CharId = 2101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Shuimu01",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarShuimu01",
		NpcSkinModelId = 8210199,
		SkinDescribe = "UI_Skin_Des_210102",
		SkinId = 210102,
		SkinModelId = 210199,
		SkinName = "UI_Skin_Name_210102",
	},
	[510101] = {
		BigIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Bust/Avatar/T_Bust_Songlu01.T_Bust_Songlu01'",
		CharId = 5101,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Songlu01",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarSonglu01",
		NpcSkinModelId = 8510199,
		SkinDescribe = "UI_Skin_Des_510101",
		SkinId = 510101,
		SkinModelId = 510199,
		SkinName = "UI_Skin_Name_510101",
	},
	[530101] = {
		BattleCharUIMap = {
			[3] = 23,
		},
		BigIcon = "Texture2D'/Game/UI/Texture/Dynamic/Image/Bust/Avatar/T_Bust_Saiqi01.T_Bust_Saiqi01'",
		CharId = 5301,
		Icon = "/Game/UI/Texture/Dynamic/Image/Head/Avatar/T_Head_Saiqi01",
		LongIcon = "/Game/UI/Texture/Dynamic/Image/Gacha/Avatar/T_Gacha_AvatarSaiqi01",
		NpcSkinModelId = 8530199,
		SkinDescribe = "UI_Skin_Des_530101",
		SkinId = 530101,
		SkinModelId = 530199,
		SkinName = "UI_Skin_Name_530101",
	},
})