-- Source Excel file path: ..\datas\SpawnNPC.xlsx
local T = {}
T.RT_1 = {
		-10,
		150,
		60,
	}
T.RT_2 = {
		-10,
		120,
		70,
	}
T.RT_3 = {
		20,
		250,
		60,
	}
T.RT_4 = {
		-15,
		220,
		50,
	}
T.RT_5 = {
		0,
		-120,
		0,
	}
T.RT_6 = {
		0,
		-50,
		0,
	}
T.RT_7 = {
		20,
		350,
		150,
	}
T.RT_8 = {
		30,
		350,
		150,
	}
T.RT_9 = {
		0,
		-70,
		0,
	}
T.RT_10 = {
		-15,
		150,
		65,
	}
T.RT_11 = {
		20,
		250,
		65,
	}
T.RT_12 = {
		0,
		150,
		65,
	}
T.RT_13 = {
		0,
		0,
		0,
	}
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("SpawnNPC", {
	[900001] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Duanzao/BP_BaiDZ",
		EndDialogue = 21000202,
		FixedCamera = "/Game/UI/UI_PC/Forging/Blueprint/BP_ForgeCamera",
		FixedCameraM = "/Game/UI/UI_PC/Forging/Blueprint/BP_ForgeCamera_Mobile",
		NPCName = "UI_Npc_Name_Duanzao",
		SpawnNPCId = 900001,
		StartDialogue = 21000201,
	},
	[900002] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/BaiSD/BP_BaiSDRegion",
		CameraPosition = T.RT_1,
		CameraPositionM = T.RT_2,
		CameraPositionStart = T.RT_3,
		CameraPositionStartM = T.RT_4,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_6,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_6,
		CameraTime = 1,
		DetectionDiatance = 100,
		EndDialogue = 21000304,
		FixedCamera = "/Game/BluePrints/Char/BP_ShopCamera",
		FixedCameraM = "/Game/BluePrints/Char/BP_ShopCamera_Mobile",
		NPCName = "UI_Npc_Name_Shangdian",
		SpawnAngle = 0,
		SpawnNPCId = 900002,
		SpawnRadius = 0.5,
		StartDialogue = 21000303,
	},
	[900003] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Setting/BP_BaiTXSetting",
		CameraPosition = {
			-15,
			250,
			150,
		},
		CameraPositionM = {
			10,
			200,
			150,
		},
		CameraPositionStart = T.RT_7,
		CameraPositionStartM = T.RT_8,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_9,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_9,
		CameraTime = 1,
		ConditionID = {
			100103,
		},
		DetectionDiatance = 100,
		EndDialogue = 21000402,
		NPCName = "UI_Npc_Name_Bai",
		SpawnAngle = 0,
		SpawnNPCId = 900003,
		SpawnRadius = 1.5,
		StartDialogue = 21000401,
	},
	[900005] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Beibao/BP_NPC_BaiBB",
		CameraPosition = T.RT_10,
		CameraPositionM = {
			-5,
			150,
			65,
		},
		CameraPositionStart = T.RT_11,
		CameraPositionStartM = T.RT_11,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_5,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_5,
		CameraTime = 1,
		ConditionID = {
			27,
		},
		DetectionDiatance = 100,
		EndDialogue = 21000102,
		NPCName = "UI_Npc_Name_Bag",
		SpawnAngle = 0,
		SpawnNPCId = 900005,
		SpawnRadius = 0.5,
		StartDialogue = 21000101,
	},
	[900010] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/BaiJT/BP_BaiJT",
		CameraPosition = T.RT_1,
		CameraPositionM = T.RT_2,
		CameraPositionStart = T.RT_3,
		CameraPositionStartM = T.RT_4,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_6,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_6,
		DetectionDiatance = 100,
		NPCName = "UI_Npc_Name_Shangdian",
		SpawnAngle = 0,
		SpawnNPCId = 900010,
		SpawnRadius = 0.5,
	},
	[910002] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Beibao/BP_NPC_BaiBB",
		CameraPosition = T.RT_12,
		CameraPositionM = {
			-25,
			120,
			50,
		},
		CameraPositionStart = T.RT_11,
		CameraPositionStartM = T.RT_4,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_6,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_6,
		CameraTime = 1,
		DetectionDiatance = 100,
		EndDialogue = 21000102,
		IsOnlyMoveCamera = true,
		NPCName = "UI_Npc_Name_Shangdian",
		SpawnAngle = 0,
		SpawnNPCId = 910002,
		SpawnRadius = 0.5,
		StartDialogue = 21000101,
	},
	[910003] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Setting/BP_BaiTXSetting",
		CameraPosition = {
			0,
			250,
			150,
		},
		CameraPositionM = {
			20,
			200,
			150,
		},
		CameraPositionStart = T.RT_7,
		CameraPositionStartM = T.RT_8,
		CameraRotation = T.RT_5,
		CameraRotationM = T.RT_9,
		CameraRotationStart = T.RT_5,
		CameraRotationStartM = T.RT_9,
		CameraTime = 1,
		DetectionDiatance = 100,
		EndDialogue = 21000504,
		FixedCamera = "/Game/UI/WBP/Play/PC/BP_PlayCamera",
		FixedCameraM = "/Game/UI/WBP/Play/Mobile/BP_PlayCamera_Mobile",
		NPCName = "UI_Npc_Name_Bai",
		SpawnAngle = 0,
		SpawnNPCId = 910003,
		SpawnRadius = 1.5,
		StartDialogue = 21000503,
	},
	[910005] = {
		BPPath = "/Game/AssetDesign/Char/Npc/BaiNpc/Bai_Beibao/BP_NPC_BaiBB",
		CameraPosition = T.RT_12,
		CameraPositionStart = T.RT_11,
		CameraRotation = T.RT_5,
		CameraRotationStart = T.RT_5,
		CameraTime = 1,
		DetectionDiatance = 100,
		EndDialogue = 21000102,
		NPCName = "UI_Npc_Name_Bag",
		SpawnAngle = 0,
		SpawnNPCId = 910005,
		SpawnRadius = 0.5,
		StartDialogue = 21000101,
	},
	[910006] = {
		CameraPosition = T.RT_13,
		CameraPositionStart = T.RT_13,
		CameraRotation = T.RT_13,
		CameraRotationStart = T.RT_13,
		FixedCamera = "/Game/BluePrints/Char/BP_ZhiLiuEntrustCamera",
		IsOnlyMoveCamera = true,
		NPCName = "UI_DGNpc_Name_NPC_Zhiliu",
		SpawnNPCId = 910006,
	},
	[910007] = {
		CameraPosition = T.RT_13,
		CameraPositionStart = T.RT_13,
		CameraRotation = T.RT_13,
		CameraRotationStart = T.RT_13,
		FixedCamera = "/Game/BluePrints/Char/BP_ZhiLiuEntrustShopCamera",
		IsOnlyMoveCamera = true,
		NPCName = "UI_DGNpc_Name_NPC_Zhiliu",
		SpawnNPCId = 910007,
	},
	[910008] = {
		BPPath = "/Game/UI/Blueprint/BP_Book_Loop.BP_Book_Loop",
		CameraPosition = T.RT_10,
		CameraPositionStart = T.RT_11,
		CameraRotation = T.RT_5,
		CameraRotationStart = T.RT_5,
		CameraTime = 1,
		DetectionDiatance = 100,
		NPCName = "UI_Wiki_Book",
		SpawnAngle = 0,
		SpawnNPCId = 910008,
		SpawnRadius = 0.5,
	},
	[920005] = {
		CameraPosition = T.RT_12,
		CameraPositionStart = T.RT_11,
		CameraRotation = T.RT_5,
		CameraRotationStart = T.RT_5,
		CameraTime = 1,
		EndDialogue = 21000102,
		FixedCamera = "/Game/BluePrints/Char/BP_ExploreBadgeShopCamera",
		FixedCameraM = "/Game/BluePrints/Char/BP_ExploreBadgeShopCamera_Mobile",
		IsOnlyMoveCamera = true,
		NPCName = "UI_Npc_Name_Bag",
		SpawnNPCId = 920005,
		StartDialogue = 21000101,
	},
})