-- Source Excel file path: ..\datas\SystemGuide.xlsx
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("SystemGuide", {
	[1001] = {
		EnterDungeon = 19,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_PartialDamage.story",
		SysGuideId = 1001,
	},
	[1002] = {
		EnterDungeon = 10,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_PartialDamage_Shijingzhe.story",
		SysGuideId = 1002,
	},
	[2001] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Delivery.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2001,
		UIUnlockRule = "Map",
	},
	[2002] = {
		GuideEnd = 1,
		GuideStoryline = "Guide/Guide_Armory_ChangeWeapon.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		SysGuideId = 2002,
		UIUnlockRule = "Armory",
	},
	[2007] = {
		ConditionCheck = 4160,
		GuideEnd = 1,
		GuideStoryline = "Guide/Guide_Mod.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		SysGuideId = 2007,
	},
	[2008] = {
		ConditionCheck = 4380,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Dungeon.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		SysGuideId = 2008,
		UIUnlockRule = "Dungeon",
	},
	[2009] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Quest.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		SysGuideId = 2009,
		UIUnlockRule = "Quest",
	},
	[2010] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Forge.story",
		IsInRegion = 1,
		OpenInterface = "ForgeMain",
		SysGuideId = 2010,
		UIUnlockRule = "Forging",
	},
	[2011] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_BattleBag.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		PreSysGuideId = 2010,
		SysGuideId = 2011,
		UIUnlockRule = "BattleWheel",
	},
	[2012] = {
		FinishQuest = 10020505,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_BattleRole.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		SysGuideId = 2012,
	},
	[2013] = {
		ConditionCheck = 4210,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_ModTendency.story",
		IsInRegion = 1,
		OpenInterface = "ArmoryMod",
		SysGuideId = 2013,
		UIUnlockRule = "Polarity",
	},
	[2014] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_HardBoss.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2014,
		UIUnlockRule = "HardBoss",
	},
	[2015] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Impression.story",
		IsInRegion = 1,
		SpecialCondition = "ImpressionTalk",
		SysGuideId = 2015,
	},
	[2016] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_BattleBag_2.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2011,
		SysGuideId = 2016,
	},
	[2017] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_BattleBag_2.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2012,
		SysGuideId = 2017,
	},
	[2018] = {
		GuideEnd = 1,
		GuideStoryline = "Guide/Guide_Gacha.story",
		IsInRegion = 1,
		OpenInterface = "GachaMain",
		SysGuideId = 2018,
	},
	[2019] = {
		EnterDungeon = 900001,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_TrainingGround_1.story",
		SysGuideId = 2019,
	},
	[2020] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_TrainingGround_2.story",
		OpenInterface = "TrainingGroundSetup",
		SysGuideId = 2020,
	},
	[2021] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_TrainingGround_3.story",
		PlayerInControl = 1,
		PreSysGuideId = 2020,
		SysGuideId = 2021,
	},
	[2022] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Modlevelup.story",
		IsInRegion = 1,
		PreSysGuideId = 2007,
		SysGuideId = 2022,
	},
	[2023] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2039,
		SysGuideId = 2023,
	},
	[2024] = {
		ConditionCheck = 5057,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge_Lantern.story",
		OpenInterface = "RougeMain",
		PreSysGuideId = 2064,
		SysGuideId = 2024,
	},
	[2026] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Shop.story",
		OpenInterface = "ShopMain",
		SysGuideId = 2026,
	},
	[2027] = {
		FinishQuestChain = 200209,
		GuideEnd = 0,
		GuideStoryline = "SpecialSideStory/2002/Maer_EmptyQuest_1.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2027,
	},
	[2028] = {
		FinishQuestChain = 200219,
		GuideEnd = 0,
		GuideStoryline = "SpecialSideStory/2002/Maer_EmptyQuest_2.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2028,
	},
	[2029] = {
		FinishQuestChain = 200208,
		GuideEnd = 0,
		GuideStoryline = "SpecialSideStory/2002/Maer_EmptyQuest_3.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2029,
	},
	[2031] = {
		GuideEnd = 1,
		GuideStoryline = "Guide/Guide_Pet2.story",
		IsInRegion = 1,
		OpenInterface = "PetCapture",
		SysGuideId = 2031,
	},
	[2032] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge_3Choose1.story",
		OpenInterface = "Rouge_Blessing_3Choose1",
		SysGuideId = 2032,
	},
	[2036] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Temple.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2036,
		UIUnlockRule = "Temple",
	},
	[2038] = {
		FinishQuest = 10020102,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_SkillPress.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2002,
		SysGuideId = 2038,
	},
	[2039] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_GroupOnlineRule.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2014,
		SysGuideId = 2039,
		UIUnlockRule = "FriendMain",
	},
	[2040] = {
		FirstSeenTag = "SpecialBreakItem3",
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Mech1.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2040,
	},
	[2041] = {
		FirstSeenTag = "SpecialBreakItem1",
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Mech2.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2041,
	},
	[2042] = {
		FirstSeenTag = "SpecialBreakItem4",
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Mech3.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2042,
	},
	[2043] = {
		FirstSeenTag = "SpecialBreakItem2",
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Mech4.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2043,
	},
	[2044] = {
		FinishQuest = 20021501,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Fish.story",
		IsInRegion = 1,
		OpenInterface = "AnglingMain",
		SysGuideId = 2044,
	},
	[2051] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_DynStory.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SpecialCondition = "FirstDynQuest",
		SysGuideId = 2051,
	},
	[2052] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Pan.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SpecialCondition = "FirstPanFixTalk",
		SysGuideId = 2052,
	},
	[2054] = {
		FinishQuest = 20022902,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_ChangeColor.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2054,
	},
	[2055] = {
		FinishQuest = 10020156,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_WIKI.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2055,
	},
	[2056] = {
		EnterDungeon = 80201,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_SideWaysJump.story",
		SysGuideId = 2056,
	},
	[2057] = {
		ConditionCheck = 4330,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Dispatch.story",
		IsInRegion = 1,
		OpenInterface = "LevelMapMain",
		SysGuideId = 2057,
		UIUnlockRule = "Dispatch",
	},
	[2058] = {
		ConditionCheck = 1,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Sojourns.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		PreSysGuideId = 2023,
		SysGuideId = 2058,
	},
	[2060] = {
		ConditionCheck = 4320,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_DailyGoalUI.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2060,
	},
	[2061] = {
		ConditionCheck = 4360,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_ModArchiveUI.story",
		IsInRegion = 1,
		OpenInterface = "BattleMain",
		PlayerInControl = 1,
		PreSysGuideId = 2022,
		SysGuideId = 2061,
	},
	[2062] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_AbyssUI.story",
		IsInRegion = 1,
		OpenInterface = "AbyssMain",
		SysGuideId = 2062,
	},
	[2063] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge_UIGuide.story",
		PlayerInControl = 1,
		PreSysGuideId = 2032,
		SysGuideId = 2063,
	},
	[2064] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge_Settlement.story",
		OpenInterface = "RougeSettlement",
		SysGuideId = 2064,
	},
	[2065] = {
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Rouge_Contract.story",
		OpenInterface = "RougeLikeContractPanel",
		SysGuideId = 2065,
	},
	[2066] = {
		ConditionCheck = 6013,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Abyss.story",
		SysGuideId = 2066,
	},
	[2067] = {
		FinishQuest = 10020101,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_Tracking.story",
		IsInRegion = 1,
		PlayerInControl = 1,
		SysGuideId = 2067,
	},
	[2068] = {
		FinishQuestChain = 200103,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_PetTrain.story",
		IsInRegion = 1,
		SysGuideId = 2068,
		UIUnlockRule = "Pet",
	},
	[2069] = {
		ConditionCheck = 4340,
		GuideEnd = 0,
		GuideStoryline = "Guide/Guide_DungeonSec.story",
		IsInRegion = 1,
		OpenInterface = "StyleOfPlay",
		PreSysGuideId = 2058,
		SysGuideId = 2069,
	},
})