-- Source Excel file path: ..\datas\Talk\TalkConfig.xlsx
local T = {}
T.RT_1 = {
		bNeedStage = true,
	}
T.RT_2 = {
		bBlendDialogueCamera = true,
		bNeedStage = true,
	}
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("TalkType", {
	AudioOnly = {
		BasicType = "Audio",
		ShowInStoryReview = false,
		TalkType = "AudioOnly",
	},
	Black = {
		BasicType = "Black",
		CameraType = "EmptyCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "Black",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_BlackScreenTalk.WBP_BlackScreenTalk_C'",
	},
	BlackISS = {
		BasicType = "Black",
		CameraType = "EmptyCamera",
		ExtraParams = {
			bBlackScreenSameScreen = true,
		},
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "BlackISS",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_BlackScreenTalk.WBP_BlackScreenTalk_C'",
	},
	Boss = {
		BasicType = "Boss",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = false,
		TalkType = "Boss",
		UICanInteractive = false,
	},
	Bubble = {
		BasicType = "Bubble",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = false,
		TalkType = "Bubble",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Dialog/BP_Empty.BP_Empty_C'",
	},
	BubbleTalk = {
		BasicType = "Bubble",
		CameraType = "FixedCamera",
		ExtraParams = T.RT_1,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = false,
		TalkType = "BubbleTalk",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Dialog/BP_Empty.BP_Empty_C'",
	},
	Cinematic = {
		BasicType = "Cinematic",
		CameraType = "SequenceCamera",
		ExtraParams = {
			bComplexCameraBlend = true,
			bNeedStage = true,
		},
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "Cinematic",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_CinematicUI.BP_CinematicUI_C'",
	},
	Drive = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = true,
		TalkType = "Drive",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_DriveTalkUI.BP_DriveTalkUI_C'",
	},
	FaultBlack = {
		BasicType = "Black",
		CameraType = "EmptyCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "FaultBlack",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_Story_FaultBlack.WBP_Story_FaultBlack'",
	},
	FixSimple = {
		BasicType = "FixSimple",
		CameraType = "FixedCamera",
		ExtraParams = T.RT_2,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "FixSimple",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_SimpleTalkUI.BP_SimpleTalkUI_C'",
	},
	ForgingGuide = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = false,
		TalkType = "ForgingGuide",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Forging/Widget/WBP_Forging_WorkableTalk.WBP_Forging_WorkableTalk_C'",
	},
	FreeSimple = {
		BasicType = "FreeSimple",
		CameraType = "FreeCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "FreeSimple",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_SimpleTalkUI.BP_SimpleTalkUI_C'",
	},
	Guide = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = true,
		TalkType = "Guide",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_Story_GuideMan.WBP_Story_GuideMan_C'",
	},
	HintGuide = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = true,
		TalkType = "HintGuide",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_Story_GuideMan.WBP_Story_GuideMan_C'",
	},
	Impression = {
		BasicType = "Impression",
		CameraType = "FreeCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "Impression",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Impression/BP_Impression_PC.BP_Impression_PC_C'",
	},
	NoIntFixSimple = {
		BasicType = "FixSimple",
		CameraType = "FixedCamera",
		ExtraParams = T.RT_2,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "NoIntFixSimple",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_SimpleTalkUI.BP_SimpleTalkUI_C'",
	},
	PanFixSimple = {
		BasicType = "FixSimple",
		CameraType = "FixedCamera",
		ExtraParams = T.RT_2,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "PanFixSimple",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_SimpleTalkUI.BP_SimpleTalkUI_C'",
	},
	QuestImpression = {
		BasicType = "FixSimple",
		CameraType = "FixedCamera",
		ExtraParams = T.RT_2,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "QuestImpression",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Impression/BP_Impression_PC.BP_Impression_PC_C'",
	},
	QueueGuide = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = true,
		TalkType = "QueueGuide",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_Story_GuideMan.WBP_Story_GuideMan_C'",
	},
	RougeLike = {
		BasicType = "RougeLike",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = false,
		TalkType = "RougeLike",
		UICanInteractive = false,
	},
	Show = {
		BasicType = "Show",
		CameraType = "SequenceCamera",
		ExtraParams = T.RT_1,
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "Show",
		UICanInteractive = true,
		UIPath = "WidgetBlueprint'/Game/UI/UI_PC/Story/BP_SimpleTalkUI.BP_SimpleTalkUI_C'",
	},
	SpecialQuestFail = {
		BasicType = "Black",
		CameraType = "EmptyCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "SpecialQuestFail",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_BlackScreenTalk.WBP_BlackScreenTalk_C'",
	},
	UnimportGuide = {
		BasicType = "Guide",
		CameraType = "PlayerCamera",
		GameInput = true,
		ShowGameUI = true,
		ShowInStoryReview = true,
		TalkType = "UnimportGuide",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_Story_GuideMan.WBP_Story_GuideMan_C'",
	},
	White = {
		BasicType = "Black",
		CameraType = "EmptyCamera",
		GameInput = false,
		SetPlayerInvincible = true,
		ShowGameUI = false,
		ShowInStoryReview = true,
		TalkType = "White",
		UICanInteractive = false,
		UIPath = "WidgetBlueprint'/Game/UI/WBP/Story/Widget/WBP_WhiteScreenTalk.WBP_WhiteScreenTalk_C'",
	},
})