-- Source Excel file path: ['..\\datas\\Talk\\FacialAndAction.xlsx', '..\\datas\\Talk\\FacialAndAction.xlsx', '..\\datas\\Talk\\FacialAndAction.xlsx', '..\\datas\\Talk\\FacialAndAction.xlsx']
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("TalkAction", {
	Afraid_End = {
		ActionMontage = "Emo_Afraid",
		AnimationId = "Afraid_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Afraid_Loop = {
		ActionMontage = "Emo_Afraid",
		AnimationId = "Afraid_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Afraid_Start = {
		ActionMontage = "Emo_Afraid",
		AnimationId = "Afraid_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Agree = {
		ActionMontage = "Emo_Agree",
		AnimationId = "Agree",
		BlendInTime = 0.4,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	AgreeHead = {
		ActionMontage = "Emo_AgreeHead",
		AnimationId = "AgreeHead",
		BlendInTime = 0.4,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Aim_Loop = {
		ActionMontage = "Aim_Idle",
		AnimationId = "Aim_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Alright_End = {
		ActionMontage = "Emo_Alright",
		AnimationId = "Alright_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
	},
	Alright_Loop = {
		ActionMontage = "Emo_Alright",
		AnimationId = "Alright_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
	},
	Alright_Start = {
		ActionMontage = "Emo_Alright",
		AnimationId = "Alright_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Angry01_End = {
		ActionMontage = "Emo_Angry01",
		AnimationId = "Angry01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Angry01_Start = {
		ActionMontage = "Emo_Angry01",
		AnimationId = "Angry01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Angry02_End = {
		ActionMontage = "Emo_Angry02",
		AnimationId = "Angry02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Angry02_Start = {
		ActionMontage = "Emo_Angry02",
		AnimationId = "Angry02_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Avoid = {
		ActionMontage = "Emo_Avoid",
		AnimationId = "Avoid",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Awa_Idle = {
		ActionMontage = "Emo_Idle",
		AnimationId = "Awa_Idle",
		BlendInTime = 0.8,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Awa_Story_Operate_End = {
		ActionMontage = "Story_Operate",
		AnimationId = "Awa_Story_Operate_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Awa_Story_Operate_Loop = {
		ActionMontage = "Story_Operate",
		AnimationId = "Awa_Story_Operate_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Awa_Story_Operate_Start = {
		ActionMontage = "Story_Operate",
		AnimationId = "Awa_Story_Operate_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_Circle_End = {
		ActionMontage = "Emo_Circle",
		AnimationId = "Bai_Circle_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Bai_Circle_Loop = {
		ActionMontage = "Emo_Circle",
		AnimationId = "Bai_Circle_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Bai_Circle_Start = {
		ActionMontage = "Emo_Circle",
		AnimationId = "Bai_Circle_Start",
		BlendInTime = 0.4,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_Idle = {
		ActionMontage = "Emo_Idle",
		AnimationId = "Bai_Idle",
		BlendInTime = 0.8,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_Shock2Think2Confident = {
		ActionMontage = "Emo_ShockTo",
		AnimationId = "Bai_Shock2Think2Confident",
		BlendInTime = 0.2,
		BlendOutTime = 1,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_SlowIdle = {
		ActionMontage = "Emo_Idle",
		AnimationId = "Bai_SlowIdle",
		BlendInTime = 1.5,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_SpecialConfident_Start = {
		ActionMontage = "Emo_SpecialConfident",
		AnimationId = "Bai_SpecialConfident_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Bai_Talk03Quick = {
		ActionMontage = "Emo_Talk03",
		AnimationId = "Bai_Talk03Quick",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "StartQuick",
		bUseIK = true,
	},
	Bai_Think2Confident = {
		ActionMontage = "Emo_ThinkTo",
		AnimationId = "Bai_Think2Confident",
		BlendInTime = 0.2,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Beibao_Dyn_Find1 = {
		ActionMontage = "Find1",
		AnimationId = "Beibao_Dyn_Find1",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Default",
	},
	Beibao_Dyn_Find2 = {
		ActionMontage = "Find2",
		AnimationId = "Beibao_Dyn_Find2",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Default",
	},
	Beibao_Dyn_Find3 = {
		ActionMontage = "Find3",
		AnimationId = "Beibao_Dyn_Find3",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Default",
	},
	Beibao_Finish = {
		ActionMontage = "Performance",
		AnimationId = "Beibao_Finish",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Finish",
		bUseIK = true,
	},
	Beibao_Start = {
		ActionMontage = "Performance",
		AnimationId = "Beibao_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Performance",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	BossSaiqi_Story_Die = {
		ActionMontage = "Story_Die",
		AnimationId = "BossSaiqi_Story_Die",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
	},
	BossSaiqi_Story_HurtCrouch = {
		ActionMontage = "Story_HurtCrouch",
		AnimationId = "BossSaiqi_Story_HurtCrouch",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
	},
	Buluchild_Story_Find = {
		ActionMontage = "Story_Find",
		AnimationId = "Buluchild_Story_Find",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Call_End = {
		ActionMontage = "Emo_Call",
		AnimationId = "Call_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Call_Loop = {
		ActionMontage = "Emo_Call",
		AnimationId = "Call_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Call_Start = {
		ActionMontage = "Emo_Call",
		AnimationId = "Call_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ChenSi_End = {
		ActionMontage = "Chensi",
		AnimationId = "ChenSi_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ChenSi_Start = {
		ActionMontage = "Chensi",
		AnimationId = "ChenSi_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToExplainL_End = {
		ActionMontage = "Emo_ConfidentLRToExplainL",
		AnimationId = "ConfidentLRToExplainL_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToExplainL_Loop = {
		ActionMontage = "Emo_ConfidentLRToExplainL",
		AnimationId = "ConfidentLRToExplainL_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToExplainL_Start = {
		ActionMontage = "Emo_ConfidentLRToExplainL",
		AnimationId = "ConfidentLRToExplainL_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToExplainR_End = {
		ActionMontage = "Emo_ConfidentLRToExplainR",
		AnimationId = "ConfidentLRToExplainR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToExplainR_Loop = {
		ActionMontage = "Emo_ConfidentLRToExplainR",
		AnimationId = "ConfidentLRToExplainR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToExplainR_Start = {
		ActionMontage = "Emo_ConfidentLRToExplainR",
		AnimationId = "ConfidentLRToExplainR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToSighL_End = {
		ActionMontage = "Emo_ConfidentLRToSighL",
		AnimationId = "ConfidentLRToSighL_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToSighL_Loop = {
		ActionMontage = "Emo_ConfidentLRToSighL",
		AnimationId = "ConfidentLRToSighL_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToSighL_Start = {
		ActionMontage = "Emo_ConfidentLRToSighL",
		AnimationId = "ConfidentLRToSighL_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToSighR_End = {
		ActionMontage = "Emo_ConfidentLRToSighR",
		AnimationId = "ConfidentLRToSighR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToSighR_Loop = {
		ActionMontage = "Emo_ConfidentLRToSighR",
		AnimationId = "ConfidentLRToSighR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToSighR_Start = {
		ActionMontage = "Emo_ConfidentLRToSighR",
		AnimationId = "ConfidentLRToSighR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToTalk01_End = {
		ActionMontage = "Emo_ConfidentLRToTalk01",
		AnimationId = "ConfidentLRToTalk01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToTalk01_Loop = {
		ActionMontage = "Emo_ConfidentLRToTalk01",
		AnimationId = "ConfidentLRToTalk01_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToTalk01_Start = {
		ActionMontage = "Emo_ConfidentLRToTalk01",
		AnimationId = "ConfidentLRToTalk01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToTalkL_End = {
		ActionMontage = "Emo_ConfidentLRToTalkL",
		AnimationId = "ConfidentLRToTalkL_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToTalkL_Loop = {
		ActionMontage = "Emo_ConfidentLRToTalkL",
		AnimationId = "ConfidentLRToTalkL_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToTalkL_Start = {
		ActionMontage = "Emo_ConfidentLRToTalkL",
		AnimationId = "ConfidentLRToTalkL_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLRToTalkR_End = {
		ActionMontage = "Emo_ConfidentLRToTalkR",
		AnimationId = "ConfidentLRToTalkR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentLR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLRToTalkR_Loop = {
		ActionMontage = "Emo_ConfidentLRToTalkR",
		AnimationId = "ConfidentLRToTalkR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLRToTalkR_Start = {
		ActionMontage = "Emo_ConfidentLRToTalkR",
		AnimationId = "ConfidentLRToTalkR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLR_End = {
		ActionMontage = "Emo_ConfidentLR",
		AnimationId = "ConfidentLR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLR_Loop = {
		ActionMontage = "Emo_ConfidentLR",
		AnimationId = "ConfidentLR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLR_Start = {
		ActionMontage = "Emo_ConfidentLR",
		AnimationId = "ConfidentLR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLToExplain_End = {
		ActionMontage = "Emo_ConfidentLToExplain_",
		AnimationId = "ConfidentLToExplain_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentL",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLToExplain_Loop = {
		ActionMontage = "Emo_ConfidentLToExplain_",
		AnimationId = "ConfidentLToExplain_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLToExplain_Start = {
		ActionMontage = "Emo_ConfidentLToExplain_",
		AnimationId = "ConfidentLToExplain_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLToSigh_End = {
		ActionMontage = "Emo_ConfidentLToSigh",
		AnimationId = "ConfidentLToSigh_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentL",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLToSigh_Loop = {
		ActionMontage = "Emo_ConfidentLToSigh",
		AnimationId = "ConfidentLToSigh_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLToSigh_Start = {
		ActionMontage = "Emo_ConfidentLToSigh",
		AnimationId = "ConfidentLToSigh_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLToTalk01_End = {
		ActionMontage = "Emo_ConfidentLToTalk01",
		AnimationId = "ConfidentLToTalk01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentL",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLToTalk01_Loop = {
		ActionMontage = "Emo_ConfidentLToTalk01",
		AnimationId = "ConfidentLToTalk01_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLToTalk01_Start = {
		ActionMontage = "Emo_ConfidentLToTalk01",
		AnimationId = "ConfidentLToTalk01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentLToTalk_End = {
		ActionMontage = "Emo_ConfidentLToTalk",
		AnimationId = "ConfidentLToTalk_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentL",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentLToTalk_Loop = {
		ActionMontage = "Emo_ConfidentLToTalk",
		AnimationId = "ConfidentLToTalk_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentLToTalk_Start = {
		ActionMontage = "Emo_ConfidentLToTalk",
		AnimationId = "ConfidentLToTalk_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentRToExplain_End = {
		ActionMontage = "Emo_ConfidentRToExplain",
		AnimationId = "ConfidentRToExplain_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentRToExplain_Loop = {
		ActionMontage = "Emo_ConfidentRToExplain",
		AnimationId = "ConfidentRToExplain_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentRToExplain_Start = {
		ActionMontage = "Emo_ConfidentRToExplain",
		AnimationId = "ConfidentRToExplain_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentRToSigh_End = {
		ActionMontage = "Emo_ConfidentRToSigh",
		AnimationId = "ConfidentRToSigh_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentRToSigh_Loop = {
		ActionMontage = "Emo_ConfidentRToSigh",
		AnimationId = "ConfidentRToSigh_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentRToSigh_Start = {
		ActionMontage = "Emo_ConfidentRToSigh",
		AnimationId = "ConfidentRToSigh_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentRToTalk01_End = {
		ActionMontage = "Emo_ConfidentRToTalk01",
		AnimationId = "ConfidentRToTalk01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentRToTalk01_Loop = {
		ActionMontage = "Emo_ConfidentRToTalk01",
		AnimationId = "ConfidentRToTalk01_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentRToTalk01_Start = {
		ActionMontage = "Emo_ConfidentRToTalk01",
		AnimationId = "ConfidentRToTalk01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentRToTalk_End = {
		ActionMontage = "Emo_ConfidentRToTalk",
		AnimationId = "ConfidentRToTalk_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_ConfidentR",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentRToTalk_Loop = {
		ActionMontage = "Emo_ConfidentRToTalk",
		AnimationId = "ConfidentRToTalk_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentRToTalk_Start = {
		ActionMontage = "Emo_ConfidentRToTalk",
		AnimationId = "ConfidentRToTalk_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ConfidentR_End = {
		ActionMontage = "Emo_ConfidentR",
		AnimationId = "ConfidentR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ConfidentR_Loop = {
		ActionMontage = "Emo_ConfidentR",
		AnimationId = "ConfidentR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ConfidentR_Start = {
		ActionMontage = "Emo_ConfidentR",
		AnimationId = "ConfidentR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Confident_End = {
		ActionMontage = "Emo_Confident",
		AnimationId = "Confident_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Confident_Loop = {
		ActionMontage = "Emo_Confident",
		AnimationId = "Confident_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Confident_Start = {
		ActionMontage = "Emo_Confident",
		AnimationId = "Confident_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Crouch = {
		ActionMontage = "Story_Crouch",
		AnimationId = "Crouch",
		BlendInTime = 0.3,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Crouch_End = {
		ActionMontage = "Story_Crouch",
		AnimationId = "Crouch_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Crouch_Start = {
		ActionMontage = "Story_Crouch",
		AnimationId = "Crouch_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Dafu_Emo_Bandge_End = {
		ActionMontage = "Emo_Bandge",
		AnimationId = "Dafu_Emo_Bandge_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Dafu_Emo_Bandge_Loop = {
		ActionMontage = "Emo_Bandge",
		AnimationId = "Dafu_Emo_Bandge_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Dafu_Emo_Bandge_Start = {
		ActionMontage = "Emo_Bandge",
		AnimationId = "Dafu_Emo_Bandge_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Dead = {
		ActionMontage = "Emo_Dead",
		AnimationId = "Dead",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Die = {
		ActionMontage = "Emo_Die",
		AnimationId = "Die",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Disagree = {
		ActionMontage = "Emo_Disagree",
		AnimationId = "Disagree",
		BlendInTime = 0.4,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	DisagreeHead = {
		ActionMontage = "Emo_DisagreeHead",
		AnimationId = "DisagreeHead",
		BlendInTime = 0.4,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Explain01L_End = {
		ActionMontage = "Emo_Explain01L",
		AnimationId = "Explain01L_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Explain01L_Start = {
		ActionMontage = "Emo_Explain01L",
		AnimationId = "Explain01L_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Explain01_End = {
		ActionMontage = "Emo_Explain01",
		AnimationId = "Explain01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Explain01_Start = {
		ActionMontage = "Emo_Explain01",
		AnimationId = "Explain01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Explain02_End = {
		ActionMontage = "Emo_Explain02",
		AnimationId = "Explain02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Explain02_Start = {
		ActionMontage = "Emo_Explain02",
		AnimationId = "Explain02_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	ExplainTwo_End = {
		ActionMontage = "Emo_ExplainTwo",
		AnimationId = "ExplainTwo_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	ExplainTwo_Start = {
		ActionMontage = "Emo_ExplainTwo",
		AnimationId = "ExplainTwo_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	FuXiong_End = {
		ActionMontage = "FuXiong",
		AnimationId = "FuXiong_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	FuXiong_Start = {
		ActionMontage = "FuXiong",
		AnimationId = "FuXiong_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Give = {
		ActionMontage = "Emo_Give",
		AnimationId = "Give",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Gun_Loop = {
		ActionMontage = "Gun_Idle",
		AnimationId = "Gun_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Hurt01 = {
		ActionMontage = "Emo_Hurt01",
		AnimationId = "Hurt01",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Interactive_End = {
		ActionMontage = "Interactive",
		AnimationId = "Interactive_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Interactive_Start = {
		ActionMontage = "Interactive",
		AnimationId = "Interactive_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_Agree = {
		ActionMontage = "Emo_Agree",
		AnimationId = "Invite_Agree",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_AgreeHead = {
		ActionMontage = "Emo_AgreeHead",
		AnimationId = "Invite_AgreeHead",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_Angry01_End = {
		ActionMontage = "Emo_Angry01",
		AnimationId = "Invite_Angry01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Confident_End = {
		ActionMontage = "Emo_Confident",
		AnimationId = "Invite_Confident_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Disagree = {
		ActionMontage = "Emo_Disagree",
		AnimationId = "Invite_Disagree",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_DisagreeHead = {
		ActionMontage = "Emo_DisagreeHead",
		AnimationId = "Invite_DisagreeHead",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_Explain01_End = {
		ActionMontage = "Emo_Explain01",
		AnimationId = "Invite_Explain01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Explain02_End = {
		ActionMontage = "Emo_Explain02",
		AnimationId = "Invite_Explain02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Give = {
		ActionMontage = "Emo_Give",
		AnimationId = "Invite_Give",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Invite_Shock_End = {
		ActionMontage = "Emo_Shock",
		AnimationId = "Invite_Shock_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Sigh_End = {
		ActionMontage = "Emo_Sigh",
		AnimationId = "Invite_Sigh_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Talk01_End = {
		ActionMontage = "Emo_Talk01",
		AnimationId = "Invite_Talk01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Talk02_End = {
		ActionMontage = "Emo_Talk02",
		AnimationId = "Invite_Talk02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Talk03_End = {
		ActionMontage = "Emo_Talk03",
		AnimationId = "Invite_Talk03_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Invite_Think_End = {
		ActionMontage = "Emo_Think",
		AnimationId = "Invite_Think_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.05,
		EndLoopMontage = "Emo_Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	JT_Mid_F_Story_Operate_End = {
		ActionMontage = "Story_Operate",
		AnimationId = "JT_Mid_F_Story_Operate_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	JT_Mid_F_Story_Operate_Loop = {
		ActionMontage = "Story_Operate",
		AnimationId = "JT_Mid_F_Story_Operate_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	JT_Mid_F_Story_Operate_Start = {
		ActionMontage = "Story_Operate",
		AnimationId = "JT_Mid_F_Story_Operate_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	JiaYou_End = {
		ActionMontage = "JiaYou",
		AnimationId = "JiaYou_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	JiaYou_Start = {
		ActionMontage = "JiaYou",
		AnimationId = "JiaYou_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Linen_Inves_End = {
		ActionMontage = "Story_Inves",
		AnimationId = "Linen_Inves_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Linen_Inves_Start = {
		ActionMontage = "Story_Inves",
		AnimationId = "Linen_Inves_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Linen_Salut_End = {
		ActionMontage = "Story_Salut",
		AnimationId = "Linen_Salut_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Linen_Salut_Start = {
		ActionMontage = "Story_Salut",
		AnimationId = "Linen_Salut_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Linen_Shot = {
		ActionMontage = "Story_Shot",
		AnimationId = "Linen_Shot",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Linen_Shotpre_End = {
		ActionMontage = "Story_Shotpre",
		AnimationId = "Linen_Shotpre_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Linen_Shotpre_Start = {
		ActionMontage = "Story_Shotpre",
		AnimationId = "Linen_Shotpre_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_Lieidle = {
		ActionMontage = "Story_Lieidle",
		AnimationId = "Lise_Lieidle",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Lise_Liewake_End = {
		ActionMontage = "Story_Liewake",
		AnimationId = "Lise_Liewake_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Lise_Sitidle",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Lise_Liewake_Start = {
		ActionMontage = "Story_Liewake",
		AnimationId = "Lise_Liewake_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_Sing_End = {
		ActionMontage = "Story_Sing",
		AnimationId = "Lise_Sing_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Lise_Sing_Start = {
		ActionMontage = "Story_Sing",
		AnimationId = "Lise_Sing_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_Sitgive_End = {
		ActionMontage = "Story_Sitgive",
		AnimationId = "Lise_Sitgive_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Lise_Sitgive_Start = {
		ActionMontage = "Story_Sitgive",
		AnimationId = "Lise_Sitgive_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Lise_Sitidle",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_Sitidle_End = {
		ActionMontage = "Story_Sitidle",
		AnimationId = "Lise_Sitidle_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Lise_Sitidle_Start = {
		ActionMontage = "Story_Sitidle",
		AnimationId = "Lise_Sitidle_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Lise_Sitidle",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_Story_Hug = {
		ActionMontage = "Story_Hug",
		AnimationId = "Lise_Story_Hug",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Lise_Touch_End = {
		ActionMontage = "Story_Touch",
		AnimationId = "Lise_Touch_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Lise_Touch_Start = {
		ActionMontage = "Story_Touch",
		AnimationId = "Lise_Touch_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Lise_hurt_Loop = {
		ActionMontage = "Emo_hurt",
		AnimationId = "Lise_hurt_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = false,
	},
	Nvzhu_Story_CrouchWithFlower = {
		ActionMontage = "Story_CrouchWithFlower",
		AnimationId = "Nvzhu_Story_CrouchWithFlower",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Nvzhu_Story_LieDown = {
		ActionMontage = "LieDown_Loop",
		AnimationId = "Nvzhu_Story_LieDown",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Nvzhu_Story_StretchHand_End = {
		ActionMontage = "Story_StretchHand",
		AnimationId = "Nvzhu_Story_StretchHand_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Nvzhu_Story_StretchHand_Start = {
		ActionMontage = "Story_StretchHand",
		AnimationId = "Nvzhu_Story_StretchHand_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	OldMan100155 = {
		ActionMontage = "Story_10015503",
		AnimationId = "OldMan100155",
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Onground01 = {
		ActionMontage = "Emo_OnGround01",
		AnimationId = "Onground01",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = false,
	},
	Onground02 = {
		ActionMontage = "Emo_OnGround02",
		AnimationId = "Onground02",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Onground03 = {
		ActionMontage = "Emo_OnGround03",
		AnimationId = "Onground03",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Pose = {
		ActionMontage = "IdleShow_01",
		AnimationId = "Pose",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Start",
		bUseIK = true,
	},
	Saiqi_Story_CrySit = {
		ActionMontage = "Story_CrySit",
		AnimationId = "Saiqi_Story_CrySit",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Saiqi_Story_HoldScythe = {
		ActionMontage = "Story_HoldScythe",
		AnimationId = "Saiqi_Story_HoldScythe",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Saiqi_Story_TiredStand = {
		ActionMontage = "Story_TiredStand",
		AnimationId = "Saiqi_Story_TiredStand",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	ScratchHead_End = {
		ActionMontage = "Emo_ScratchHead",
		AnimationId = "ScratchHead_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
	},
	ScratchHead_Loop = {
		ActionMontage = "Emo_ScratchHead",
		AnimationId = "ScratchHead_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
	},
	ScratchHead_Start = {
		ActionMontage = "Emo_ScratchHead",
		AnimationId = "ScratchHead_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Shangdian_Write_Start = {
		ActionMontage = "Write",
		AnimationId = "Shangdian_Write_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = false,
	},
	Shock02_End = {
		ActionMontage = "Emo_Shock02",
		AnimationId = "Shock02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Shock02_Loop = {
		ActionMontage = "Emo_Shock02",
		AnimationId = "Shock02_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Shock02_Start = {
		ActionMontage = "Emo_Shock02",
		AnimationId = "Shock02_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Shock_End = {
		ActionMontage = "Emo_Shock",
		AnimationId = "Shock_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Shock_Loop = {
		ActionMontage = "Emo_Shock",
		AnimationId = "Shock_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Shock_Start = {
		ActionMontage = "Emo_Shock",
		AnimationId = "Shock_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Sigh_End = {
		ActionMontage = "Emo_Sigh",
		AnimationId = "Sigh_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Sigh_Loop = {
		ActionMontage = "Emo_Sigh",
		AnimationId = "Sigh_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Sigh_Start = {
		ActionMontage = "Emo_Sigh",
		AnimationId = "Sigh_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Sit = {
		ActionMontage = "Interactive_Sit_F",
		AnimationId = "Sit",
		BlendInTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "SitStart",
		bUseIK = true,
	},
	Sit03 = {
		ActionMontage = "Interactive_Sit03",
		AnimationId = "Sit03",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Sit_End = {
		ActionMontage = "Interactive_Sit_F",
		AnimationId = "Sit_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.1,
		IsSpecialAnim = false,
		MontageSection = "SitEndF",
		bUseIK = true,
	},
	Sit_Loop = {
		ActionMontage = "Interactive_Sit_F",
		AnimationId = "Sit_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.1,
		IsSpecialAnim = false,
		MontageSection = "SitLoop",
		bUseIK = true,
	},
	Sit_Start = {
		ActionMontage = "Interactive_Sit_F",
		AnimationId = "Sit_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "SitStart",
		bUseIK = true,
	},
	SpecialConfident_End = {
		ActionMontage = "Emo_SpecialConfident",
		AnimationId = "SpecialConfident_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	SpecialConfident_Start = {
		ActionMontage = "Emo_SpecialConfident",
		AnimationId = "SpecialConfident_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	SpecialHappy_End = {
		ActionMontage = "Emo_SpecialHappy",
		AnimationId = "SpecialHappy_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	SpecialHappy_Start = {
		ActionMontage = "Emo_SpecialHappy",
		AnimationId = "SpecialHappy_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	SpecialHoldHelmet_End = {
		ActionMontage = "Emo_SpecialHoldHelmet",
		AnimationId = "SpecialHoldHelmet_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
	},
	SpecialHoldHelmet_Start = {
		ActionMontage = "Emo_SpecialHoldHelmet",
		AnimationId = "SpecialHoldHelmet_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	SpecialIdle01 = {
		ActionMontage = "SpecialIdle01",
		AnimationId = "SpecialIdle01",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Default",
	},
	SpecialIdle02 = {
		ActionMontage = "SpecialIdle02",
		AnimationId = "SpecialIdle02",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = true,
		MontageSection = "Default",
	},
	SpecialLook01_Start = {
		ActionMontage = "Emo_SpecialLook01",
		AnimationId = "SpecialLook01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	SpecialLook02_Start = {
		ActionMontage = "Emo_SpecialLook02",
		AnimationId = "SpecialLook02_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	SpecialSnapFingers = {
		ActionMontage = "Emo_SpecialSnapFingers",
		AnimationId = "SpecialSnapFingers",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	SpecialThink_End = {
		ActionMontage = "Emo_SpecialThink",
		AnimationId = "SpecialThink_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	SpecialThink_Start = {
		ActionMontage = "Emo_SpecialThink",
		AnimationId = "SpecialThink_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	SpecialUnInterested_End = {
		ActionMontage = "Emo_SpecialUnInterested",
		AnimationId = "SpecialUnInterested_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
	},
	SpecialUnInterested_Start = {
		ActionMontage = "Emo_SpecialUnInterested",
		AnimationId = "SpecialUnInterested_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Special_End = {
		ActionMontage = "Emo_Special",
		AnimationId = "Special_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Special_Start = {
		ActionMontage = "Emo_Special",
		AnimationId = "Special_Start",
		BlendInTime = 0.3,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Special_Start1 = {
		ActionMontage = "Emo_Special",
		AnimationId = "Special_Start1",
		BlendInTime = 0.3,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start1",
		bUseIK = true,
	},
	Special_Start2 = {
		ActionMontage = "Emo_Special",
		AnimationId = "Special_Start2",
		BlendInTime = 0.3,
		BlendOutTime = 0.4,
		IsSpecialAnim = false,
		MontageSection = "Start2",
		bUseIK = true,
	},
	Squat_End = {
		ActionMontage = "Emo_Squat",
		AnimationId = "Squat_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
	},
	Squat_Start = {
		ActionMontage = "Emo_Squat",
		AnimationId = "Squat_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Stop01_End = {
		ActionMontage = "Emo_Stop01",
		AnimationId = "Stop01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Stop01_Start = {
		ActionMontage = "Emo_Stop01",
		AnimationId = "Stop01_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Story_HandToHand_End = {
		ActionMontage = "Story_HandToHand",
		AnimationId = "Story_HandToHand_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Story_HandToHand_Loop = {
		ActionMontage = "Story_HandToHand",
		AnimationId = "Story_HandToHand_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Story_HandToHand_Start = {
		ActionMontage = "Story_HandToHand",
		AnimationId = "Story_HandToHand_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Story_Hug = {
		ActionMontage = "Story_Hug",
		AnimationId = "Story_Hug",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	TakePhoto = {
		ActionMontage = "Emo_TakePhoto",
		AnimationId = "TakePhoto",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
	},
	Talk01_End = {
		ActionMontage = "Emo_Talk01",
		AnimationId = "Talk01_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk01_Loop = {
		ActionMontage = "Emo_Talk01",
		AnimationId = "Talk01_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Talk01_Start = {
		ActionMontage = "Emo_Talk01",
		AnimationId = "Talk01_Start",
		BlendInTime = 0.4,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Talk02_End = {
		ActionMontage = "Emo_Talk02",
		AnimationId = "Talk02_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk02_Start = {
		ActionMontage = "Emo_Talk02",
		AnimationId = "Talk02_Start",
		BlendInTime = 0.4,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Talk03ToTalkL_End = {
		ActionMontage = "Emo_Talk03ToTalkL",
		AnimationId = "Talk03ToTalkL_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_Talk03",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk03ToTalkL_Loop = {
		ActionMontage = "Emo_Talk03ToTalkL",
		AnimationId = "Talk03ToTalkL_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Talk03ToTalkL_Start = {
		ActionMontage = "Emo_Talk03ToTalkL",
		AnimationId = "Talk03ToTalkL_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Talk03ToTalkR_End = {
		ActionMontage = "Emo_Talk03ToTalkR",
		AnimationId = "Talk03ToTalkR_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_Talk03",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk03ToTalkR_Loop = {
		ActionMontage = "Emo_Talk03ToTalkR",
		AnimationId = "Talk03ToTalkR_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Talk03ToTalkR_Start = {
		ActionMontage = "Emo_Talk03ToTalkR",
		AnimationId = "Talk03ToTalkR_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Talk03ToThink_End = {
		ActionMontage = "Emo_Talk03ToThink",
		AnimationId = "Talk03ToThink_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Emo_Talk03",
		EndLoopMontageSection = "Loop",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk03ToThink_Loop = {
		ActionMontage = "Emo_Talk03ToThink",
		AnimationId = "Talk03ToThink_Loop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Talk03ToThink_Start = {
		ActionMontage = "Emo_Talk03ToThink",
		AnimationId = "Talk03ToThink_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Talk03_End = {
		ActionMontage = "Emo_Talk03",
		AnimationId = "Talk03_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Talk03_Loop = {
		ActionMontage = "Emo_Talk03",
		AnimationId = "Talk03_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Talk03_Start = {
		ActionMontage = "Emo_Talk03",
		AnimationId = "Talk03_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tanshou_End = {
		ActionMontage = "TanShou",
		AnimationId = "Tanshou_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		EndLoopMontage = "Idle",
		EndLoopMontageSection = "Start",
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Tanshou_Start = {
		ActionMontage = "TanShou",
		AnimationId = "Tanshou_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Think_End = {
		ActionMontage = "Emo_Think",
		AnimationId = "Think_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Think_Loop = {
		ActionMontage = "Emo_Think",
		AnimationId = "Think_Loop",
		BlendInTime = 0,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Think_Start = {
		ActionMontage = "Emo_Think",
		AnimationId = "Think_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	TieJiang_Idle = {
		ActionMontage = "Emo_Idle",
		AnimationId = "TieJiang_Idle",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tuosi02_Dodge_End = {
		ActionMontage = "Story_Dodge",
		AnimationId = "Tuosi02_Dodge_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Tuosi02_Dodge_Start = {
		ActionMontage = "Story_Dodge",
		AnimationId = "Tuosi02_Dodge_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tuosi02_Drop = {
		ActionMontage = "Story_Drop",
		AnimationId = "Tuosi02_Drop",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tuosi02_Sitidle = {
		ActionMontage = "Story_Sitidle",
		AnimationId = "Tuosi02_Sitidle",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tuosi02_Threat_End = {
		ActionMontage = "Story_Threat",
		AnimationId = "Tuosi02_Threat_End",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "End",
		bUseIK = true,
	},
	Tuosi02_Threat_Start = {
		ActionMontage = "Story_Threat",
		AnimationId = "Tuosi02_Threat_Start",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Tuosi02_Touch = {
		ActionMontage = "Story_Touch",
		AnimationId = "Tuosi02_Touch",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Weiji_Story_Sit = {
		ActionMontage = "Story_Sit",
		AnimationId = "Weiji_Story_Sit",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Weita_Idle = {
		ActionMontage = "Emo_Idle",
		AnimationId = "Weita_Idle",
		BlendInTime = 0.8,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Start",
		bUseIK = true,
	},
	Weita_Story_Crouch_Loop = {
		ActionMontage = "Story_Crouch",
		AnimationId = "Weita_Story_Crouch_Loop",
		BlendInTime = 0,
		BlendOutTime = 0,
		IsSpecialAnim = false,
		MontageSection = "Loop",
		bUseIK = true,
	},
	Wuyou_Agree = {
		ActionMontage = "Idle_random1",
		AnimationId = "Wuyou_Agree",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Default",
	},
	Wuyou_Born = {
		ActionMontage = "Born",
		AnimationId = "Wuyou_Born",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Default",
	},
	Wuyou_Disagree = {
		ActionMontage = "Idle_random2",
		AnimationId = "Wuyou_Disagree",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Default",
	},
	Wuyou_Disappear = {
		ActionMontage = "Disappear",
		AnimationId = "Wuyou_Disappear",
		BlendInTime = 0.2,
		BlendOutTime = 0.2,
		IsSpecialAnim = false,
		MontageSection = "Default",
	},
})