-- Source Excel file path: ..\datas\Quest.xlsx
local T = {}
T.RT_1 = {
		0,
		0,
	}
T.RT_2 = {
		"RDT_RarelyData",
		"RDT_CommonData",
	}
T.RT_3 = {
		"RDT_QuestData",
		"RDT_CommonData",
		"RDT_None",
	}
T.RT_4 = {
		0.5,
		0.5,
	}
T.RT_5 = {
		"All",
	}
T.RT_6 = {
		"RDT_QuestData",
		"RDT_CommonData",
	}
T.RT_7 = {
		Type = "On",
	}
local ReadOnly = (DataMgr or {})["ReadOnly"] or function(n, x) return x end
return ReadOnly("UniversalConfig", {
	[101] = {
		FinishBlackScreen = true,
		FinishBlackScreenFadeIn = true,
		FinishBlackScreenFadeOut = true,
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_4,
		RegionDataType = {
			"RDT_QuestData",
		},
		SetPlayerTransform = "QuestPoint_IcelakeHunting_Defence",
		UniversalConfigId = 101,
	},
	[102] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		UniversalConfigId = 102,
	},
	[103] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		UniversalConfigId = 103,
	},
	[104] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_5,
		UniversalConfigId = 104,
	},
	[105] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_5,
		UniversalConfigId = 105,
	},
	[106] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		PlayBlackScreen = T.RT_4,
		SetPlayerTransform = "QuestPoint_SaiqiWalkStart",
		UniversalConfigId = 106,
	},
	[107] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		SetPlayerTransform = "QuestPoint_SaiqiWalk_GetCamera",
		UniversalConfigId = 107,
	},
	[109] = {
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 109,
	},
	[110] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		SetPlayerTransform = "QuestPoint_ShijingzheBossBattle",
		UniversalConfigId = 110,
	},
	[111] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_5,
		UniversalConfigId = 111,
	},
	[112] = {
		DisableBattleWheel = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 112,
	},
	[113] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInActiveInteractive = T.RT_7,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_3,
		UniversalConfigId = 113,
	},
	[114] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInActiveInteractive = T.RT_7,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_3,
		UniversalConfigId = 114,
	},
	[117] = {
		IfChangeESC = 1,
		IfInActiveInteractive = T.RT_7,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_3,
		UniversalConfigId = 117,
	},
	[1001] = {
		DisableBattleWheel = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInActiveInteractive = {
			Id = {
				1,
				2,
			},
			Type = "Part",
		},
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		PlayBlackScreen = T.RT_1,
		SetPlayerTransform = "Point1",
		UniversalConfigId = 1001,
	},
	[1003] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		PlayBlackScreen = T.RT_1,
		RegionDataType = {
			"RDT_CommonData",
		},
		SetPlayerTransform = "QuestPoint_LizhanBossBattle",
		UniversalConfigId = 1003,
	},
	[1004] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		SetPlayerTransform = "BP_TargetPoint110104",
		UniversalConfigId = 1004,
	},
	[1005] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1005,
	},
	[1006] = {
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1006,
	},
	[1008] = {
		FinishBlackScreenFadeIn = true,
		FinishBlackScreenFadeOut = true,
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1008,
	},
	[1009] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_3,
		UniversalConfigId = 1009,
	},
	[1010] = {
		DisableBattleWheel = true,
		FinishBlackScreenFadeOut = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1010,
	},
	[1011] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		SetPlayerTransform = "QuestPoint_LizhanBossBattle",
		UniversalConfigId = 1011,
	},
	[1012] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1012,
	},
	[1013] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 1013,
	},
	[1014] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1014,
	},
	[1015] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1015,
	},
	[1017] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1017,
	},
	[1018] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1018,
	},
	[1019] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1019,
	},
	[1021] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1021,
	},
	[1023] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1023,
	},
	[1024] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = {
			0,
			1,
		},
		RegionDataType = T.RT_2,
		UniversalConfigId = 1024,
	},
	[1025] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1025,
	},
	[1026] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 1026,
	},
	[1030] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1030,
	},
	[1031] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 1031,
	},
	[1032] = {
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1032,
	},
	[1033] = {
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1033,
	},
	[1034] = {
		DisableBattleWheel = true,
		FinishBlackScreen = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1034,
	},
	[1035] = {
		FinishBlackScreen = true,
		IfChangeESC = 1,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1035,
	},
	[1036] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1036,
	},
	[1037] = {
		DisableBattleWheel = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_6,
		UniversalConfigId = 1037,
	},
	[1040] = {
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		IsBossBattle = true,
		RegionDataType = T.RT_5,
		UniversalConfigId = 1040,
	},
	[1047] = {
		IfChangeESC = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		UniversalConfigId = 1047,
	},
	[1048] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_2,
		UniversalConfigId = 1048,
	},
	[2001] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_5,
		SetPlayerTransform = "QuestPoint_Nai01StartPoint",
		UniversalConfigId = 2001,
	},
	[2002] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = T.RT_5,
		SetPlayerTransform = "pNai02",
		UniversalConfigId = 2002,
	},
	[2003] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 2003,
	},
	[2004] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 2004,
	},
	[2005] = {
		IfChangeESC = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		UniversalConfigId = 2005,
	},
	[2006] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		RegionDataType = T.RT_5,
		SetPlayerTransform = "QuestPoint_Batt01StartPoint",
		UniversalConfigId = 2006,
	},
	[12000208] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_4,
		RegionDataType = T.RT_5,
		UniversalConfigId = 12000208,
	},
	[12000307] = {
		DisableBattleWheel = true,
		HideBattlePet = true,
		HideBattleWheel = true,
		IfChangeESC = 1,
		IfDestoryPhantom = 1,
		IfInitPlayer = true,
		IfStartStoryMode = 1,
		IfWaitDead = 1,
		PlayBlackScreen = T.RT_1,
		RegionDataType = {
			"RDT_RarelyData",
		},
		UniversalConfigId = 12000307,
	},
})